"""Initialize the database and seed it from committed word-bank data files.

Seeding is **data-file driven** (``backend/data/wordbanks/*.json``, generated by
``scripts/build_wordbanks.py`` from ECDICT) and **idempotent** — running it
repeatedly never duplicates rows, so it is safe to run on every container start
and inside tests. No network access is required at runtime (SOU-39).
"""

import json
from pathlib import Path
from typing import Dict, List

from sqlalchemy.orm import Session

from app.database import SessionLocal, init_db
from app.models.user import User
from app.models.word import Word, WordBank
from passlib.context import CryptContext

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

DATA_DIR = Path(__file__).parent / "data" / "wordbanks"

# Single source of truth for the test account (ADR-0010: test / 123456).
TEST_USERNAME = "test"
TEST_EMAIL = "test@example.com"
TEST_PASSWORD = "123456"


def load_wordbank_files(data_dir: Path = DATA_DIR) -> List[dict]:
    """Load every word-bank JSON seed file, sorted by filename for determinism."""
    files = sorted(Path(data_dir).glob("*.json"))
    banks: List[dict] = []
    for path in files:
        with open(path, encoding="utf-8") as fh:
            banks.append(json.load(fh))
    return banks


def seed_word_banks(db: Session, data_dir: Path = DATA_DIR) -> Dict[str, int]:
    """Seed word banks from data files. Idempotent: existing banks are skipped.

    Returns a mapping of bank name -> number of words inserted this run
    (0 for banks that already existed).
    """
    stats: Dict[str, int] = {}
    for bank_data in load_wordbank_files(data_dir):
        name = bank_data["name"]
        if db.query(WordBank).filter(WordBank.name == name).first():
            stats[name] = 0  # already seeded
            continue

        words_data = bank_data.get("words", [])
        bank = WordBank(
            name=name,
            description=bank_data.get("description"),
            # total_words mirrors the actual number of words for API consistency.
            total_words=len(words_data),
        )
        db.add(bank)
        db.flush()  # assign bank.id before inserting words

        db.bulk_save_objects(
            [
                Word(
                    word_bank_id=bank.id,
                    spelling=w["spelling"],
                    phonetic=w.get("phonetic"),
                    meaning=w["meaning"],
                    example_sentence=w.get("example_sentence"),
                    order_index=w["order_index"],
                )
                for w in words_data
            ]
        )
        stats[name] = len(words_data)
    db.commit()
    return stats


def seed_test_user(db: Session) -> bool:
    """Create the shared test account if missing (idempotent). Returns True if created."""
    if db.query(User).filter(User.username == TEST_USERNAME).first():
        return False
    db.add(
        User(
            username=TEST_USERNAME,
            email=TEST_EMAIL,
            hashed_password=pwd_context.hash(TEST_PASSWORD),
        )
    )
    db.commit()
    return True


def seed_database(db: Session, data_dir: Path = DATA_DIR) -> Dict[str, int]:
    """Seed word banks and the test user in one idempotent call."""
    stats = seed_word_banks(db, data_dir)
    seed_test_user(db)
    return stats


def main() -> None:
    print("🚀 Initializing database...")
    init_db()
    print("📦 Seeding word banks from data files...")
    db = SessionLocal()
    try:
        stats = seed_database(db)
    finally:
        db.close()

    total = sum(stats.values())
    for name, count in stats.items():
        status = f"{count} words" if count else "already seeded"
        print(f"   - {name}: {status}")
    print(f"   - test user (username: {TEST_USERNAME}, password: {TEST_PASSWORD})")
    print(f"✨ Done! ({len(stats)} word banks, {total} words inserted this run)")


if __name__ == "__main__":
    main()
