"""Initialize database and seed word-bank data.

Word banks and words are loaded from the committed seed files under
``backend/data/wordbanks/`` (generated by ``scripts/build_wordbanks.py`` from
the MIT-licensed ECDICT dictionary). A single test user is also created for
local development and E2E tests.
"""

from sqlalchemy.orm import Session
from passlib.context import CryptContext

from app.database import SessionLocal, init_db
from app.models.user import User
from app.models.word import WordBank
from app.seed import seed_wordbanks

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


def create_test_user(db: Session) -> None:
    """Create the default test user if it does not already exist."""
    if db.query(User).filter(User.username == "test").first():
        print("⚠️  Test user already exists, skipping")
        return
    db.add(User(
        username="test",
        email="test@example.com",
        hashed_password=pwd_context.hash("123456"),
    ))
    db.commit()
    print("   - 1 test user (username: test, password: 123456)")


def create_sample_data() -> None:
    """Seed word banks/words from data files and create the test user."""
    db: Session = SessionLocal()
    try:
        created = seed_wordbanks(db)
        if created:
            banks = db.query(WordBank).all()
            total_words = sum(b.total_words for b in banks)
            print("✅ Word banks seeded successfully!")
            print(f"   - {created} word banks, {total_words} words total")
            for b in banks:
                print(f"     · {b.name}: {b.total_words} 词")
        else:
            print("⚠️  Database already has word banks, skipping seed")

        create_test_user(db)
    except Exception as e:
        print(f"❌ Error seeding data: {e}")
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    print("🚀 Initializing database...")
    init_db()
    print("📦 Seeding data...")
    create_sample_data()
    print("✨ Done!")
