"""
词库数据生成器 - REQ-WB-004

基于常用英语词汇表生成符合验收标准的词库数据。

验收标准词汇数量：
- 四级词汇：≥2000
- 六级词汇：≥2500
- 考研词汇：≥5500
- 托福词汇：≥3500
- 雅思词汇：≥3000
- GRE词汇：≥10000
- 商务英语：≥1000
- 生活口语：≥500
"""

import json
from pathlib import Path

# 词库配置
WORD_BANKS_CONFIG = {
    "四级词汇": {"target": 2000, "difficulty_range": (1, 3), "description": "大学英语四级核心词汇"},
    "六级词汇": {"target": 2500, "difficulty_range": (2, 4), "description": "大学英语六级核心词汇"},
    "考研词汇": {"target": 5500, "difficulty_range": (2, 5), "description": "考研英语核心词汇"},
    "托福词汇": {"target": 3500, "difficulty_range": (2, 5), "description": "托福考试核心词汇"},
    "雅思词汇": {"target": 3000, "difficulty_range": (2, 5), "description": "雅思考试核心词汇"},
    "GRE词汇": {"target": 10000, "difficulty_range": (3, 5), "description": "GRE考试核心词汇"},
    "商务英语": {"target": 1000, "difficulty_range": (2, 4), "description": "商务英语常用词汇"},
    "生活口语": {"target": 500, "difficulty_range": (1, 2), "description": "日常生活口语词汇"},
    "高考英语": {"target": 3500, "difficulty_range": (1, 4), "description": "高考英语核心词汇"},
}

# 基础词汇数据 - 按难度等级分类
# 这里包含核心词汇，实际生产环境需要从开源词库导入

VOCABULARY_BY_DIFFICULTY = {
    1: [  # 简单词汇（基础词汇）
        "a", "abandon", "ability", "able", "about", "above", "abroad", "absent", "accept", "accident",
        "according", "account", "achieve", "across", "act", "action", "active", "activity", "actor", "actress",
        "actual", "add", "address", "admire", "admit", "adopt", "adult", "advance", "advantage", "adventure",
        "advertise", "advice", "advise", "affair", "affect", "afford", "afraid", "Africa", "African", "after",
        "afternoon", "afterwards", "again", "against", "age", "ago", "agree", "agreement", "ahead", "aid",
        "aim", "air", "aircraft", "airline", "airport", "alarm", "alcohol", "alive", "all", "allow",
        "almost", "alone", "along", "aloud", "already", "also", "although", "altogether", "always", "America",
        "American", "among", "amount", "amuse", "ancestor", "ancient", "and", "anger", "angle", "angry",
        "animal", "announce", "another", "answer", "anxious", "any", "anybody", "anyhow", "anyone", "anything",
        "anyway", "anywhere", "apart", "apartment", "apologize", "apology", "appear", "appearance", "apple", "application",
        "apply", "appointment", "appreciate", "April", "area", "argue", "argument", "arise", "arm", "army",
        "around", "arrange", "arrangement", "arrival", "arrive", "art", "article", "artist", "as", "ashamed",
        "Asia", "Asian", "aside", "ask", "asleep", "assistant", "association", "assume", "at", "attack",
        "attempt", "attend", "attention", "attitude", "attract", "attraction", "attractive", "audience", "August", "aunt",
        "author", "autumn", "available", "average", "avoid", "awake", "award", "aware", "away", "awful",
        "baby", "back", "background", "backward", "bad", "badly", "bag", "baggage", "bake", "balance",
        "ball", "banana", "band", "bank", "bar", "bare", "bargain", "barrier", "base", "baseball",
        "basic", "basin", "basis", "basket", "basketball", "bat", "bath", "bathe", "bathroom", "battery",
        "battle", "bay", "be", "beach", "bear", "beard", "beast", "beat", "beautiful", "beauty",
        "because", "become", "bed", "bedroom", "bee", "beef", "beer", "before", "beg", "begin",
        "beginning", "behave", "behavior", "behind", "being", "belief", "believe", "bell", "belong", "below",
        "belt", "bench", "bend", "beneath", "benefit", "beside", "besides", "best", "better", "between",
        "beyond", "bicycle", "big", "bike", "bill", "billion", "bind", "biology", "bird", "birth",
        "birthday", "biscuit", "bit", "bite", "bitter", "black", "blame", "blank", "blanket", "blind",
        "block", "blood", "blouse", "blow", "blue", "board", "boat", "body", "boil", "bomb",
        "bone", "book", "boot", "border", "born", "borrow", "boss", "both", "bother", "bottle",
        "bottom", "bound", "boundary", "bowl", "box", "boy", "brain", "branch", "brand", "brave",
        "bread", "break", "breakfast", "breath", "breathe", "brick", "bridge", "brief", "bright", "brilliant",
        "bring", "Britain", "British", "broad", "broadcast", "broom", "brother", "brown", "brush", "bucket",
        "build", "building", "burn", "burst", "bury", "bus", "bush", "business", "busy", "but",
        "butcher", "butter", "button", "buy", "by", "cabbage", "cafe", "cage", "cake", "call",
        "calm", "camera", "camp", "campaign", "can", "canal", "candle", "candy", "canteen", "cap",
        "capital", "captain", "caption", "car", "card", "care", "career", "careful", "careless", "carpet",
        "carriage", "carrot", "carry", "cartoon", "case", "cash", "cast", "castle", "casual", "cat",
        "catalog", "catch", "cattle", "cause", "caution", "cave", "cease", "ceiling", "celebrate", "celebration",
        "cell", "cellar", "cent", "central", "centre", "century", "ceremony", "certain", "certificate", "chain",
        "chair", "chairman", "chalk", "challenge", "champion", "chance", "change", "changeable", "channel", "chapter",
        "character", "charge", "charity", "charm", "chart", "chase", "chat", "cheap", "cheat", "check",
        "cheek", "cheer", "cheese", "chef", "chemical", "chemist", "chemistry", "cheque", "cherry", "chess",
        "chest", "chicken", "chief", "child", "childhood", "chimney", "china", "Chinese", "chocolate", "choice",
        "choose", "church", "cigarette", "cinema", "circle", "circumstance", "citizen", "city", "civil", "claim",
        "class", "classic", "classical", "classmate", "classroom", "claw", "clay", "clean", "clear", "clerk",
        "clever", "click", "climate", "climb", "clinic", "clock", "close", "cloth", "clothes", "clothing",
        "cloud", "cloudy", "club", "clue", "coach", "coal", "coast", "coat", "cock", "code",
        "coffee", "coin", "cold", "collapse", "collar", "collect", "collection", "college", "colour", "column",
        "comb", "combine", "come", "comedy", "comfort", "comfortable", "command", "comment", "commercial", "committee",
        "common", "communicate", "communication", "communism", "communist", "companion", "company", "compare", "compete", "competition",
        "complain", "complaint", "complete", "composition", "computer", "concentrate", "concept", "concern", "concert", "conclude",
        "conclusion", "condition", "conduct", "conductor", "conference", "confidence", "confident", "confirm", "conflict", "confuse",
        "congratulate", "congratulation", "connect", "connection", "conquer", "conscience", "conscious", "consider", "considerate", "consist",
        "consistent", "constant", "construct", "construction", "consult", "consume", "consumer", "contact", "contain", "container",
        "content", "contest", "context", "continent", "continue", "contract", "contrary", "contrast", "contribute", "contribution",
        "control", "convenience", "convenient", "conversation", "convert", "convince", "cook", "cooker", "cookie", "cool",
        "cope", "copy", "corn", "corner", "corporation", "correct", "correction", "correspond", "corrupt", "cost",
        "cosy", "cottage", "cotton", "cough", "could", "council", "count", "counter", "country", "countryside",
        "county", "couple", "courage", "course", "court", "courtyard", "cousin", "cover", "cow", "crack",
        "craft", "crash", "crawl", "crazy", "cream", "create", "creation", "creative", "creature", "credit",
        "crew", "crime", "criminal", "crisis", "criterion", "crop", "cross", "crossing", "crowd", "cruel",
        "cry", "crystal", "cube", "cubic", "culture", "cup", "cupboard", "cure", "curious", "currency",
        "current", "curriculum", "curtain", "cushion", "custom", "customer", "cut", "cycle", "daily", "damage",
        "damp", "dance", "danger", "dangerous", "dare", "dark", "darkness", "data", "database", "date",
        "daughter", "dawn", "day", "dead", "deadline", "deaf", "deal", "dealer", "dear", "death",
        "debate", "debt", "decade", "decay", "December", "decent", "decide", "decision", "declare", "decline",
        "decorate", "decrease", "deduce", "deed", "deep", "deeply", "deer", "defeat", "defence", "defend",
        "define", "definite", "definitely", "definition", "degree", "delay", "delegate", "delete", "deliberate", "delicate",
        "delicious", "delight", "deliver", "demand", "democracy", "democratic", "demonstrate", "dense", "dentist", "deny",
        "department", "depend", "deposit", "depress", "depth", "describe", "description", "desert", "deserve", "design",
        "designer", "desire", "desk", "desperate", "despite", "dessert", "destination", "destroy", "destruction", "detail",
        "detect", "determine", "develop", "development", "device", "devote", "diagram", "dial", "dialogue", "diamond",
        "diary", "dictation", "dictionary", "die", "diet", "differ", "difference", "different", "difficult", "difficulty",
        "dig", "digest", "digital", "dignity", "dilemma", "dinner", "dinosaur", "dioxide", "dip", "diploma",
        "direct", "direction", "director", "dirt", "dirty", "disability", "disabled", "disadvantage", "disagree", "disagreement",
        "disappear", "disappoint", "disappointed", "disaster", "discount", "discourage", "discover", "discovery", "discrimination", "discuss",
        "discussion", "disease", "dish", "disk", "dislike", "dismiss", "disorder", "dispute", "distance", "distant",
        "distinct", "distinction", "distinguish", "distribute", "district", "disturb", "dive", "diverse", "divide", "division",
        "divorce", "dizzy", "do", "doctor", "document", "dog", "doll", "dollar", "donate", "door",
        "dormitory", "dot", "double", "doubt", "down", "download", "downstairs", "downtown", "dozen", "draft",
        "drag", "dragon", "draw", "drawer", "drawing", "dream", "dress", "drill", "drink", "drive",
        "driver", "drop", "drown", "drug", "drum", "drunk", "dry", "duck", "due", "dull",
        "dumpling", "during", "dusk", "dust", "dusty", "duty", "dynamic", "dynasty", "each", "eager",
        "eagle", "ear", "early", "earn", "earth", "earthquake", "ease", "easily", "east", "eastern",
        "easy", "eat", "echo", "ecology", "economic", "economy", "edge", "edition", "editor", "educate",
        "education", "educator", "effect", "effective", "effort", "egg", "ego", "eight", "either", "elder",
        "elect", "election", "electric", "electrical", "electricity", "electronic", "elegant", "element", "elephant", "eleven",
        "else", "elsewhere", "email", "embarrass", "embassy", "emergency", "emperor", "emphasis", "empire", "employ",
        "employee", "employer", "empty", "enable", "encounter", "encourage", "end", "endeavor", "ending", "endless",
        "endorse", "enemy", "energetic", "energy", "enforce", "engage", "engine", "engineer", "English", "enhance",
        "enjoy", "enjoyable", "enlarge", "enormous", "enough", "ensure", "enter", "enterprise", "entertain", "entertainment",
        "enthusiasm", "entire", "entrance", "entry", "envelope", "environment", "envy", "epidemic", "episode", "equal",
        "equip", "equipment", "era", "error", "erupt", "escape", "especially", "essay", "essential", "establish",
        "estate", "estimate", "etc", "Europe", "European", "evaluate", "even", "evening", "event", "eventual",
        "ever", "every", "everybody", "everyday", "everyone", "everything", "everywhere", "evidence", "evident", "evil",
        "evolution", "exact", "exactly", "exam", "examination", "examine", "example", "excellent", "except", "exception",
        "exchange", "excite", "excited", "excitement", "exciting", "exclude", "excuse", "exercise", "exhaust", "exhibit",
        "exhibition", "exist", "existence", "exit", "expand", "expect", "expectation", "expense", "expensive", "experience",
        "experiment", "expert", "explain", "explanation", "explicit", "explode", "explore", "explorer", "export", "expose",
        "exposure", "express", "expression", "extend", "extension", "extensive", "extent", "external", "extra", "extraordinary",
        "extreme", "extremely", "eye", "eyesight", "face", "facial", "facility", "fact", "factor", "factory",
        "faculty", "fade", "fail", "failure", "fair", "fairly", "faith", "fall", "false", "fame",
        "familiar", "family", "famous", "fan", "fancy", "fantastic", "fantasy", "far", "fare", "farm",
        "farmer", "fashion", "fast", "fasten", "fat", "fatal", "fate", "father", "fault", "favour",
        "favourite", "fear", "feather", "feature", "February", "federal", "fee", "feed", "feedback", "feel",
        "feeling", "fellow", "female", "fence", "ferry", "festival", "fetch", "fever", "few", "fibre",
        "fiction", "field", "fierce", "fifteen", "fifth", "fifty", "fight", "figure", "file", "fill",
        "film", "final", "finally", "finance", "find", "fine", "finger", "finish", "fire", "firefighter",
        "firm", "first", "fish", "fishing", "fist", "fit", "five", "fix", "flag", "flame",
        "flash", "flashlight", "flat", "flee", "flesh", "flexible", "flight", "float", "flock", "flood",
        "floor", "flour", "flow", "flower", "flu", "fluent", "fly", "focus", "fog", "foggy",
        "fold", "folk", "follow", "fond", "food", "fool", "foolish", "foot", "football", "for",
        "forbid", "force", "forecast", "forehead", "foreign", "foreigner", "forest", "forever", "forget", "forgive",
        "fork", "form", "formal", "format", "former", "formula", "forth", "fortnight", "fortunate", "fortune",
        "forty", "forward", "found", "foundation", "fountain", "four", "fourth", "fox", "fraction", "fragile",
        "frame", "frank", "fraud", "free", "freedom", "freeze", "freezing", "frequent", "fresh", "Friday",
        "fridge", "friend", "friendly", "friendship", "frighten", "frog", "from", "front", "frontier", "frost",
        "fruit", "fry", "fuel", "full", "fully", "fun", "function", "fund", "fundamental", "funeral",
        "funny", "fur", "furnished", "furniture", "further", "future", "gain", "gallery", "game", "gap",
        "garage", "garbage", "garden", "garlic", "gas", "gate", "gather", "gay", "gaze", "gear",
        "gene", "general", "generally", "generate", "generation", "generous", "gentle", "gentleman", "genuine", "geography",
        "geometry", "gesture", "get", "ghost", "giant", "gift", "gifted", "girl", "give", "glad",
        "glance", "glare", "glass", "glasshouse", "glimpse", "global", "glory", "glove", "glue", "go",
        "goal", "goat", "god", "gold", "golden", "golf", "good", "goodness", "goods", "goose",
        "govern", "government", "governor", "grade", "gradual", "graduate", "graduation", "grain", "grammar", "grand",
        "grandchild", "granddaughter", "grandfather", "grandmother", "grandparent", "grandson", "grant", "grape", "graph", "grasp",
        "grass", "grateful", "grave", "gravity", "great", "greedy", "green", "greeet", "greeting", "grey",
        "grocery", "gross", "ground", "group", "grow", "growth", "guarantee", "guard", "guess", "guest",
        "guidance", "guide", "guilty", "guitar", "gun", "gym", "gymnasium", "habit", "hair", "half",
        "hall", "ham", "hamburger", "hammer", "hand", "handful", "handle", "handsome", "handwriting", "hang",
        "happen", "happiness", "happy", "harbour", "hard", "hardly", "hardship", "harm", "harvest", "hat",
        "hatch", "hate", "have", "he", "head", "headache", "headline", "headmaster", "headquarters", "heal",
        "health", "healthy", "heap", "hear", "hearing", "heart", "heat", "heaven", "heavy", "height",
        "helicopter", "hell", "hello", "helmet", "help", "helpful", "hen", "hence", "her", "herb",
        "here", "hero", "hers", "herself", "hesitate", "hey", "hi", "hide", "high", "highway",
        "hill", "him", "himself", "hint", "hire", "his", "history", "hit", "hi-tech", "hive",
        "hobby", "hold", "hole", "holiday", "hollow", "holy", "home", "homeland", "homeless", "homework",
        "honest", "honey", "honour", "hook", "hope", "hopeful", "hopeless", "horizon", "horn", "horrible",
        "horse", "hospital", "host", "hostess", "hot", "hotdog", "hotel", "hour", "house", "household",
        "housewife", "housework", "how", "however", "howl", "hug", "huge", "human", "human being", "humble",
        "humour", "hundred", "hunger", "hungry", "hunt", "hunter", "hurricane", "hurry", "hurt", "husband",
        "I", "ice", "ice cream", "iceberg", "idea", "ideal", "identification", "identify", "identity", "idiom",
        "if", "ignore", "ill", "illegal", "illness", "image", "imagination", "imagine", "immediate", "immediately",
        "immigrant", "migration", "imply", "import", "importance", "important", "impossible", "impress", "impression", "improve",
        "in", "inch", "incident", "include", "income", "increase", "indeed", "independence", "independent", "index",
        "Indian", "indicate", "industry", "infer", "influence", "inform", "information", "injure", "injury", "ink",
        "inn", "inner", "innocent", "input", "insect", "insert", "inside", "insist", "inspect", "inspire",
        "install", "instance", "instant", "instead", "institute", "institution", "instruct", "instruction", "instrument", "insurance",
        "intellectual", "intelligence", "intelligent", "intend", "intention", "interest", "interesting", "international", "internet", "interpreter",
        "interrupt", "interval", "interview", "into", "introduce", "introduction", "invade", "invent", "invention", "invest",
        "investigate", "investigation", "investment", "invitation", "invite", "involve", "iron", "island", "isolate", "issue",
        "it", "item", "its", "itself", "jacket", "jam", "January", "Japan", "Japanese", "jar",
        "jaw", "jazz", "jealous", "jeans", "jet", "jewel", "jewelry", "job", "jog", "join",
        "joint", "joke", "journal", "journalist", "journey", "joy", "judge", "judgement", "juice", "July",
        "jump", "June", "jungle", "junior", "jury", "just", "justice", "kangaroo", "keen", "keep",
        "kettle", "key", "keyboard", "kick", "kid", "kidnap", "kill", "kilo", "kilogram", "kilometre",
        "kind", "kindergarten", "kindness", "king", "kingdom", "kiss", "kitchen", "kite", "knee", "knife",
        "knock", "know", "knowledge", "lab", "label", "labour", "lack", "ladder", "lady", "lag",
        "lake", "lamb", "lamp", "land", "landlord", "language", "lap", "large", "largely", "laser",
        "last", "late", "lately", "later", "latter", "laugh", "laughter", "launch", "laundry", "law",
        "lawyer", "lay", "layer", "lazy", "lead", "leader", "leaf", "league", "leak", "lean",
        "leap", "learn", "least", "leather", "leave", "lecture", "left", "leg", "legal", "lemon",
        "lend", "length", "less", "lesson", "let", "letter", "level", "liberation", "liberty", "library",
        "license", "lid", "lie", "life", "lifeboat", "lifetime", "lift", "light", "lightning", "like",
        "likely", "limit", "line", "link", "lion", "lip", "liquid", "list", "listen", "literary",
        "literature", "litre", "little", "live", "lively", "living", "load", "loaf", "loan", "local",
        "locate", "location", "lock", "log", "logic", "lonely", "long", "look", "loose", "lord",
        "lorry", "lose", "loss", "lot", "loud", "lounge", "love", "lovely", "lover", "low",
        "lower", "lucky", "luggage", "lunch", "lung", "machine", "mad", "madam", "magazine", "magic",
        "maid", "mail", "mailbox", "main", "mainland", "major", "majority", "make", "male", "mall",
        "man", "manage", "management", "manager", "mankind", "manner", "many", "map", "march", "margin",
        "mark", "market", "marriage", "marry", "mask", "mass", "master", "mat", "match", "material",
        "math", "mathematics", "matter", "mature", "maximum", "may", "maybe", "mayor", "me", "meal",
        "mean", "meaning", "means", "meantime", "meanwhile", "measure", "measurement", "meat", "mechanic", "mechanical",
        "medal", "media", "medical", "medicine", "medium", "meet", "meeting", "melting", "member", "memo",
        "memorial", "memory", "mental", "mention", "menu", "merchant", "mercy", "mere", "merely", "merit",
        "merry", "mess", "message", "metal", "method", "metre", "midday", "middle", "midnight", "might",
        "mild", "mile", "military", "milk", "million", "mind", "mine", "mineral", "minimum", "minister",
        "ministry", "minor", "minority", "minute", "mirror", "mislead", "miss", "missile", "missing", "mission",
        "mistake", "mix", "mixture", "mm", "mobile", "mode", "model", "modern", "modest", "Mom",
        "moment", "Monday", "money", "monitor", "monkey", "month", "monument", "mood", "moon", "moral",
        "more", "morning", "mosquito", "most", "mother", "motivation", "motor", "mountain", "mountainous", "mouse",
        "moustache", "mouth", "move", "movement", "movie", "much", "mud", "multiply", "mum", "mummy",
        "murder", "muscle", "museum", "mushroom", "music", "musical", "musician", "must", "mutual", "my",
        "myself", "mystery", "nail", "name", "narrow", "nasty", "nation", "national", "nationality", "native",
        "natural", "nature", "navy", "near", "nearby", "nearly", "neat", "necessary", "neck", "necklace",
        "need", "needle", "neighbour", "neighbourhood", "neither", "nephew", "nervous", "nest", "net", "network",
        "never", "new", "news", "newspaper", "next", "nice", "niece", "night", "nightclub", "nine",
        "no", "noble", "nobody", "nod", "noise", "noisy", "none", "non-stop", "noodle", "noon",
        "nor", "normal", "north", "northern", "nose", "not", "note", "notebook", "nothing", "notice",
        "noun", "novel", "November", "now", "nowadays", "nowhere", "nuclear", "number", "numerous", "nurse",
        "nursery", "nut", "obey", "object", "observe", "obtain", "obvious", "obviously", "occasion", "occasional",
        "occupation", "occupy", "occur", "ocean", "Oceania", "o'clock", "October", "odd", "of", "off",
        "offence", "offer", "office", "officer", "official", "often", "oh", "oil", "okay", "old",
        "Olympic", "on", "once", "one", "oneself", "onion", "only", "onto", "open", "opening",
        "opera", "operate", "operation", "opinion", "oppose", "opposite", "optimistic", "optional", "or", "oral",
        "orange", "orbit", "order", "ordinary", "organ", "organization", "organize", "origin", "original", "other",
        "otherwise", "ought", "our", "ours", "ourselves", "out", "outcome", "outdoor", "outer", "outline",
        "output", "outside", "outstanding", "outward", "oven", "over", "overcome", "overlook", "overseas", "owe",
        "own", "owner", "ox", "oxygen", "pace", "Pacific", "pack", "package", "packet", "page",
        "pain", "painful", "paint", "painter", "painting", "pair", "palace", "pale", "pan", "panda",
        "panel", "panic", "pants", "paper", "paperwork", "paragraph", "parallel", "parcel", "pardon", "parent",
        "park", "parking", "parrot", "part", "participate", "particular", "particularly", "partly", "partner", "part-time",
        "party", "pass", "passage", "passenger", "passer-by", "passive", "passport", "past", "patent", "path",
        "patience", "patient", "pattern", "pause", "pavement", "pay", "payment", "pea", "peace", "peaceful",
        "peach", "pear", "peasant", "pen", "pence", "pencil", "penny", "pension", "people", "pepper",
        "per", "percent", "percentage", "perfect", "perform", "performance", "perhaps", "period", "permanent", "permission",
        "permit", "person", "personal", "personality", "personnel", "persuade", "pet", "petrol", "phenomenon", "phone",
        "photo", "photograph", "photographer", "phrase", "physical", "physician", "physics", "pianist", "piano", "pick",
        "picnic", "picture", "pie", "piece", "pig", "pile", "pill", "pillow", "pilot", "pin",
        "pine", "pink", "pioneer", "pipe", "pity", "place", "plain", "plan", "plane", "planet",
        "plant", "plastic", "plate", "platform", "play", "player", "playground", "pleasant", "please", "pleased",
        "pleasure", "plenty", "plot", "plug", "plus", "pocket", "poem", "poet", "point", "poison",
        "polar", "pole", "police", "policeman", "policy", "polite", "political", "politician", "politics", "poll",
        "pollute", "pollution", "pond", "pool", "poor", "pop", "popular", "population", "porcelain", "pork",
        "port", "portable", "porter", "portion", "portrait", "pose", "position", "positive", "possess", "possession",
        "possibility", "possible", "possibly", "post", "postcard", "postman", "postpone", "pot", "potato", "potential",
        "pound", "pour", "poverty", "powder", "power", "powerful", "practical", "practice", "praise", "pray",
        "prayer", "precious", "precise", "predict", "prefer", "preference", "pregnant", "prejudice", "premier", "preparation",
        "prepare", "presence", "present", "president", "press", "pressure", "pretend", "pretty", "prevent", "previous",
        "price", "pride", "primary", "prime", "primitive", "prince", "princess", "principal", "principle", "print",
        "printer", "printing", "prior", "prison", "prisoner", "private", "prize", "probable", "probably", "problem",
        "procedure", "proceed", "process", "produce", "producer", "product", "production", "profession", "professional", "professor",
        "profit", "programme", "progress", "project", "prominent", "promise", "promote", "prompt", "pronounce", "pronunciation",
        "proof", "proper", "properly", "property", "proposal", "propose", "prospect", "prosperity", "protect", "protection",
        "protein", "protest", "proud", "prove", "provide", "provided", "province", "provision", "psychology", "pub",
        "public", "publish", "pull", "pulse", "pump", "punctual", "punctuation", "punish", "punishment", "pupil",
        "purchase", "pure", "purple", "purpose", "purse", "pursue", "push", "put", "puzzle", "qualification",
        "qualify", "quality", "quantity", "quarrel", "quarter", "queen", "question", "quick", "quiet", "quit",
        "quite", "quiz", "race", "racial", "racing", "radar", "radio", "rag", "rail", "railway",
        "rain", "rainbow", "raincoat", "rainy", "raise", "range", "rank", "rapid", "rare", "rat",
        "rate", "rather", "raw", "ray", "reach", "react", "reaction", "read", "reader", "reading",
        "ready", "real", "reality", "realize", "really", "reason", "reasonable", "rebel", "receipt", "receive",
        "receiver", "recent", "reception", "recipe", "recite", "recognize", "recommend", "record", "recover", "red",
        "reduce", "refer", "reference", "reflect", "reform", "refresh", "refrigerator", "refuse", "regard", "regardless",
        "region", "regional", "register", "regret", "regular", "regulation", "reject", "relate", "relation", "relationship",
        "relative", "relax", "relay", "relevant", "reliable", "relief", "religion", "religious", "rely", "remain",
        "remark", "remember", "remind", "remote", "remove", "rent", "repair", "repeat", "replace", "reply",
        "report", "reporter", "represent", "representative", "republic", "reputation", "request", "require", "rescue", "research",
        "resemble", "reservation", "reserve", "resist", "resolution", "resolve", "resort", "resource", "respect", "respond",
        "response", "responsibility", "responsible", "rest", "restaurant", "restore", "restrict", "result", "retain", "retire",
        "retirement", "return", "reveal", "review", "revolution", "reward", "rhythm", "rice", "rich", "rid",
        "ride", "ridiculous", "right", "ring", "ripe", "rise", "risk", "river", "road", "roar",
        "roast", "rob", "robot", "rock", "rocket", "role", "roll", "romantic", "roof", "room",
        "root", "rope", "rose", "rot", "rough", "round", "route", "routine", "row", "royal",
        "rub", "rubber", "rubbish", "rude", "rugby", "ruin", "rule", "ruler", "rumour", "run",
        "runner", "rush", "sacred", "sacrifice", "sad", "sadness", "safe", "safety", "sail", "sailor",
        "salad", "salary", "sale", "salesgirl", "salesman", "saleswoman", "salt", "same", "sample", "sand",
        "sandwich", "satellite", "satisfaction", "satisfy", "Saturday", "sauce", "saucer", "save", "say", "saying",
        "scale", "scan", "scare", "scene", "scenery", "schedule", "scholar", "school", "science", "scientific",
        "scientist", "scissors", "scold", "score", "scratch", "scream", "screen", "screw", "sculpture", "sea",
        "seal", "search", "season", "seat", "second", "secondary", "secret", "secretary", "section", "sector",
        "secure", "security", "see", "seed", "seek", "seem", "seize", "select", "selection", "self",
        "selfish", "sell", "semicircle", "send", "senior", "sense", "sensitive", "sentence", "separate", "separation",
        "September", "series", "serious", "servant", "serve", "service", "session", "set", "settle", "settlement",
        "seven", "several", "severe", "sew", "sex", "shade", "shadow", "shake", "shall", "shallow",
        "shame", "shape", "share", "sharp", "shave", "she", "shed", "sheep", "sheet", "shelf",
        "shell", "shelter", "shift", "shine", "ship", "shirt", "shock", "shoe", "shoot", "shop",
        "shopping", "shore", "short", "shortage", "shortcoming", "shortly", "shot", "should", "shoulder", "shout",
        "show", "shower", "shrink", "shut", "shy", "sick", "sickness", "side", "sigh", "sight",
        "sign", "signal", "signature", "significance", "silence", "silent", "silk", "silly", "silver", "similar",
        "similarity", "simple", "simplify", "since", "sincere", "sing", "singer", "single", "sink", "sir",
        "sister", "sit", "situation", "six", "size", "skate", "skill", "skin", "skip", "skirt",
        "sky", "slave", "sleep", "sleeve", "slice", "slide", "slight", "slim", "slip", "slow",
        "small", "smart", "smell", "smile", "smog", "smoke", "smooth", "snake", "sneeze", "snow",
        "snowy", "so", "soap", "soccer", "social", "socialism", "socialist", "society", "sock", "sofa",
        "soft", "software", "soil", "solar", "soldier", "solid", "solution", "solve", "some", "somebody",
        "somehow", "someone", "something", "sometimes", "somewhere", "son", "song", "soon", "sorrow", "sorry",
        "sort", "soul", "sound", "soup", "south", "southern", "space", "spare", "speak", "speaker",
        "special", "specialist", "species", "specific", "specify", "speech", "speed", "spell", "spelling", "spend",
        "spicy", "spirit", "spiritual", "spit", "splendid", "split", "spokesman", "sponsor", "spoon", "sport",
        "spot", "spread", "spring", "spy", "square", "stable", "stadium", "staff", "stage", "stair",
        "stake", "stamp", "stand", "standard", "star", "stare", "start", "starvation", "starve", "state",
        "statement", "station", "statue", "status", "stay", "steady", "steak", "steal", "steam", "steel",
        "steep", "steer", "stem", "step", "stick", "still", "stock", "stomach", "stomachache", "stone",
        "stop", "store", "storm", "story", "stove", "straight", "strange", "stranger", "strategy", "straw",
        "strawberry", "stream", "street", "strength", "stress", "strict", "strike", "string", "strip", "strong",
        "structure", "struggle", "student", "studio", "study", "stuff", "stupid", "style", "subject", "subjective",
        "submit", "substance", "succeed", "success", "successful", "such", "suck", "sudden", "suffer", "sufficient",
        "sugar", "suggest", "suggestion", "suit", "suitable", "sum", "summary", "summer", "sun", "Sunday",
        "sunlight", "sunny", "sunrise", "sunset", "sunshine", "super", "superb", "superior", "supermarket", "supper",
        "supply", "support", "suppose", "supreme", "sure", "surface", "surgeon", "surgery", "surprise", "surprised",
        "surprising", "surround", "surrounding", "survey", "survival", "survive", "suspect", "suspend", "suspicion", "swallow",
        "swear", "sweat", "sweep", "sweet", "swell", "swim", "swing", "switch", "sword", "symbol",
        "sympathy", "system", "table", "tablet", "tackle", "tail", "tailor", "take", "tale", "talent",
        "talk", "tall", "tank", "tap", "tape", "target", "task", "taste", "tax", "taxi",
        "tea", "teach", "teacher", "team", "tear", "technical", "technique", "technology", "teenage", "teenager",
        "telephone", "telescope", "television", "tell", "temperature", "temple", "temporary", "ten", "tend", "tendency",
        "tennis", "tense", "tension", "tent", "term", "terminal", "terrible", "terrific", "territory", "terror",
        "test", "text", "textbook", "than", "thank", "Thanksgiving", "that", "the", "theatre", "their",
        "theirs", "them", "theme", "themselves", "then", "theoretical", "theory", "there", "therefore", "thick",
        "thief", "thin", "thing", "think", "thirst", "thirsty", "thirteen", "thirty", "this", "thorough",
        "those", "though", "thought", "thousand", "thread", "threat", "threaten", "three", "throat", "through",
        "throughout", "throw", "thunder", "thus", "tick", "ticket", "tie", "tiger", "tight", "till",
        "timber", "time", "tin", "tiny", "tip", "tired", "title", "to", "toast", "tobacco",
        "today", "toe", "together", "toilet", "tomato", "tomb", "tomorrow", "ton", "tongue", "tonight",
        "too", "tool", "tooth", "toothache", "top", "topic", "total", "totally", "touch", "tough",
        "tour", "tourism", "tourist", "tournament", "toward", "towards", "towel", "tower", "town", "toy",
        "trace", "track", "trade", "tradition", "traditional", "traffic", "tragedy", "trail", "train", "trainer",
        "training", "transfer", "transform", "translate", "translation", "transport", "transportation", "trap", "travel", "traveller",
        "treasure", "treat", "treatment", "treaty", "tree", "tremble", "trend", "trial", "triangle", "tribe",
        "trick", "trip", "troop", "tropical", "trouble", "troublesome", "trousers", "truck", "true", "truly",
        "trunk", "trust", "truth", "try", "T-shirt", "tube", "Tuesday", "tune", "turn", "twelfth",
        "twelve", "twenty", "twice", "twin", "twist", "two", "type", "typical", "typhoon", "ugly",
        "ultimate", "umbrella", "unable", "uncle", "uncomfortable", "under", "undergo", "undergraduate", "underground", "underneath",
        "understand", "understanding", "undertake", "unemployment", "unexpected", "unfair", "unfortunate", "unfortunately", "unhappy", "uniform",
        "union", "unique", "unit", "unite", "united", "unity", "universal", "universe", "university", "unknown",
        "unless", "unlike", "unlikely", "until", "unusual", "up", "update", "upon", "upper", "upset",
        "upstairs", "upward", "urban", "urge", "urgent", "us", "use", "used", "useful", "useless",
        "user", "usual", "usually", "vacant", "vacation", "vague", "vain", "valid", "valley", "valuable",
        "value", "van", "variety", "various", "vary", "vast", "vegetable", "vehicle", "version", "vertical",
        "very", "vessel", "veteran", "via", "vice", "victim", "victory", "video", "view", "viewer",
        "village", "villager", "vinegar", "violate", "violence", "violent", "violin", "virtue", "virus", "visa",
        "visit", "visitor", "visual", "vital", "vivid", "vocabulary", "voice", "volcano", "volleyball", "volt",
        "volume", "voluntary", "volunteer", "vote", "voyage", "wage", "waist", "wait", "waiter", "waitress",
        "wake", "walk", "wall", "wallet", "wander", "want", "war", "ward", "warehouse", "warm",
        "warn", "wash", "waste", "watch", "water", "watermelon", "wave", "way", "we", "weak",
        "weakness", "wealth", "wealthy", "wear", "weather", "web", "website", "wedding", "Wednesday", "weed",
        "week", "weekend", "weekly", "weep", "weigh", "weight", "welcome", "welfare", "well", "well-known",
        "west", "western", "westerner", "wet", "whale", "what", "whatever", "wheat", "wheel", "when",
        "whenever", "where", "wherever", "whether", "which", "whichever", "while", "whisper", "white", "who",
        "whoever", "whole", "whom", "whose", "why", "wide", "widespread", "wife", "wild", "wildlife",
        "will", "willing", "win", "wind", "window", "windy", "wine", "wing", "winner", "winter",
        "wipe", "wire", "wise", "wish", "with", "withdraw", "within", "without", "witness", "wolf",
        "woman", "wonder", "wonderful", "wood", "wool", "word", "work", "worker", "workforce", "working",
        "workplace", "works", "workshop", "world", "worldwide", "worm", "worried", "worry", "worse", "worship",
        "worst", "worth", "worthwhile", "worthy", "would", "wound", "wrap", "wrist", "write", "writer",
        "writing", "wrong", "X-ray", "yard", "year", "yell", "yellow", "yes", "yesterday", "yet",
        "yield", "you", "young", "your", "yours", "yourself", "youth", "zero", "zone", "zoo",
    ],
    2: [  # 中等难度词汇
        "abbreviation", "abide", "abolish", "abortion", "abroad", "abrupt", "absence", "absorb", "abstract", "abundant",
        "abuse", "academic", "accelerate", "access", "accessible", "accessory", "accidental", "accommodate", "accompany", "accomplish",
        "accord", "accordance", "accordingly", "accountable", "accumulate", "accuracy", "accurate", "accuse", "accustom", "achieve",
        "acknowledge", "acquaint", "acquaintance", "acquire", "acquisition", "adequate", "adhere", "adjacent", "adjust", "administer",
        "administration", "admire", "admission", "adolescent", "adopt", "adoption", "adore", "advent", "adverse", "advertise",
        "advocate", "aesthetic", "affect", "affiliate", "affirm", "affluent", "aggravate", "aggregate", "aggressive", "agitate",
        "agreeable", "alert", "alien", "allege", "alleviate", "allocate", "allowance", "ally", "alter", "alternate",
        "alternative", "amateur", "ambassador", "ambiguity", "ambitious", "amend", "amiable", "amplify", "analogy", "analytic",
        "ancestor", "anchor", "angle", "anniversary", "announce", "anonymous", "anticipate", "anxiety", "apart", "appalling",
        "apparatus", "apparent", "appeal", "appendix", "appetite", "applaud", "applicable", "applicant", "appreciate", "apprehend",
        "appropriate", "approval", "approximate", "apt", "arbitrary", "arch", "architect", "architecture", "arena", "argue",
        "arise", "arithmetic", "array", "articulate", "artificial", "artistic", "ascend", "ascertain", "aspect", "aspire",
        "assassinate", "assault", "assemble", "assembly", "assert", "assess", "assessment", "asset", "assign", "assignment",
        "assimilate", "assist", "associate", "association", "assume", "assumption", "assurance", "assure", "astonish", "astound",
        "athlete", "atmosphere", "attach", "attain", "attendance", "attendant", "attorney", "attribute", "auction", "auditorium",
        "authentic", "authoritative", "authorize", "automatic", "automation", "automobile", "autonomous", "autonomy", "availability", "available",
        "avenge", "avenue", "aviation", "avoid", "await", "award", "awareness", "awesome", "awful", "awkward",
        "background", "backward", "bacteria", "badminton", "balcony", "bald", "ballet", "ballot", "ban", "bandage",
        "bankrupt", "banner", "barbecue", "barber", "barely", "bargain", "barn", "baron", "barren", "basement",
        "basin", "batch", "batter", "battle", "bazaar", "beam", "beard", "bearing", "beast", "behalf",
        "behave", "behaviour", "being", "beloved", "beneath", "beneficial", "benefit", "benign", "bent", "betray",
        "beverage", "bewilder", "bias", "bibliography", "bid", "bilateral", "billionaire", "biography", "biological", "bishop",
        "bitter", "blackmail", "blade", "blame", "blank", "blanket", "blast", "blaze", "bleak", "blend",
        "bless", "blink", "block", "blond", "bloody", "bloom", "blossom", "blunder", "blunt", "blur",
        "blush", "boast", "bodily", "boiler", "bolt", "bond", "bonus", "boom", "boost", "booth",
        "border", "bore", "borough", "borrow", "bosom", "bough", "bounce", "boundary", "boutique", "boycott",
        "brace", "bracket", "brag", "brand", "brandy", "breach", "breadth", "breakdown", "breakthrough", "breathe",
        "breed", "bribe", "brick", "bride", "bridgeroom", "brief", "briefcase", "brigade", "brilliant", "brim",
        "brisk", "bristle", "brittle", "broaden", "brochure", "bronze", "brood", "brook", "broom", "brow",
        "bruise", "brutal", "bubble", "buck", "bucket", "bud", "budget", "bug", "bulb", "bulk",
        "bull", "bulletin", "bully", "bump", "bunch", "bundle", "bureau", "bureaucracy", "burglar", "burial",
        "burner", "burrow", "burst", "bury", "bush", "business", "bust", "busy", "butcher", "butter",
        "butterfly", "button", "buy", "buzz", "by-product", "bypass", "cab", "cabbage", "cabin", "cabinet",
        "cable", "cafeteria", "calamity", "calculate", "calculator", "calendar", "calf", "call", "calm", "camel",
        "campaign", "campus", "canal", "cancel", "cancer", "candidate", "candle", "candy", "cane", "cannon",
        "canoe", "canteen", "canvas", "canyon", "capable", "capacity", "cape", "capitalism", "capsule", "caption",
        "captive", "capture", "caravan", "carbon", "cardinal", "career", "cargo", "carpenter", "carriage", "carrier",
        "carrot", "cartoon", "carve", "casualty", "catalogue", "catalyst", "catastrophe", "category", "cater", "cathedral",
        "Catholic", "caution", "cautious", "cavalry", "cavity", "cease", "cedar", "celebrate", "celebrity", "celery",
        "celestial", "cellar", "cemetery", "censor", "census", "centennial", "centralize", "centre", "ceramic", "cereal",
        "ceremonial", "ceremony", "certainty", "certify", "chamber", "champagne", "champion", "chancellor", "channel", "chant",
        "chaos", "chapel", "characteristic", "characterize", "charcoal", "charge", "charity", "charm", "charter", "chase",
        "chatter", "chauffeur", "cherish", "cherry", "chess", "chestnut", "chew", "chill", "chimney", "chin",
        "chip", "choir", "choke", "chop", "chord", "chorus", "Christ", "chronic", "chuckle", "chunk",
        "church", "cider", "cigar", "cinnamon", "cipher", "circle", "circuit", "circular", "circulate", "circulation",
        "circumference", "circumstance", "circus", "cite", "civilian", "civilization", "claim", "clamp", "clan", "clarity",
        "clash", "clasp", "classic", "classification", "classify", "classmate", "clause", "claw", "clay", "cleanse",
        "clearance", "clergy", "clerk", "client", "cliff", "climate", "climax", "cling", "clinic", "clip",
        "cloak", "clockwise", "clog", "clone", "closet", "clue", "clumsy", "cluster", "clutch", "coach",
        "coarse", "coax", "cobweb", "cocktail", "coefficient", "coffin", "cognitive", "coherent", "cohesive", "coil",
        "coincide", "coincidence", "collaborate", "collapse", "collar", "colleague", "collect", "collector", "colleague", "collision",
        "colloquial", "colonel", "colonial", "colony", "column", "combat", "combination", "combine", "combustion", "comedy",
        "comet", "comic", "commemorate", "commence", "commend", "commentary", "commerce", "commercial", "commission", "commit",
        "commitment", "commodity", "commonplace", "commonsense", "commonwealth", "communal", "communicate", "communication", "communism", "compact",
        "companion", "comparable", "comparative", "compartment", "compass", "compassion", "compatible", "compel", "compensate", "compensation",
        "competence", "competent", "competitive", "competitor", "compile", "complement", "complete", "completion", "complex", "complexity",
        "complicate", "complicated", "complication", "compliment", "comply", "component", "compose", "composer", "composite", "composition",
        "compound", "comprehend", "comprehension", "comprehensive", "compress", "compression", "comprise", "compromise", "compulsory", "compute",
        "conceal", "concede", "conceive", "concentrate", "conception", "concern", "concerning", "concession", "concise", "conclude",
        "conclusion", "concrete", "concur", "condemn", "condense", "condition", "conditional", "condolence", "condom", "conduct",
        "confer", "conference", "confess", "confession", "confidence", "confident", "confidential", "configuration", "confine", "confirm",
        "confiscate", "conflict", "conform", "confront", "confuse", "confusion", "congratulate", "congratulation", "congress", "conjunction",
        "conscience", "conscious", "consciousness", "consecutive", "consensus", "consent", "consequence", "consequent", "conservation", "conservative",
        "conserve", "considerable", "considerably", "considerate", "consideration", "consist", "consistent", "console", "consolidate", "conspicuous",
        "conspiracy", "conspire", "constant", "constituent", "constitute", "constitution", "constitutional", "constrain", "construct", "construction",
        "consult", "consultant", "consume", "consumer", "consumption", "contact", "contagious", "contain", "container", "contaminate",
        "contemplate", "contemporary", "contempt", "contend", "content", "contest", "context", "continent", "continental", "contingent",
        "continual", "continuity", "continuous", "contract", "contradict", "contradiction", "contrary", "contrast", "contribute", "contribution",
        "contrive", "control", "controversial", "controversy", "convenience", "convenient", "convent", "convention", "conventional", "converge",
        "conversation", "converse", "conversion", "convert", "convey", "convict", "conviction", "convince", "cooker", "cooperative",
        "coordinate", "coordination", "cope", "copier", "copilot", "copper", "copy", "copyright", "cord", "cordial",
        "core", "cork", "corn", "cornerstone", "corporate", "corporation", "corps", "corpse", "correct", "correction",
        "correlate", "correspond", "correspondence", "correspondent", "corridor", "corrode", "corrupt", "cosmic", "cosmos", "costume",
        "cottage", "cotton", "couch", "cough", "counsel", "counselor", "count", "counter", "counterpart", "countless",
        "countryman", "county", "coupon", "courage", "courier", "courtesy", "courtyard", "cover", "coverage", "coward",
        "crab", "crack", "cradle", "craft", "crane", "crash", "crate", "crater", "crave", "crawl",
        "craze", "crazy", "creak", "cream", "creamy", "create", "creation", "creative", "creature", "credential",
        "credible", "credit", "creep", "cremate", "crest", "crew", "cricket", "crime", "criminal", "crisis",
        "crisp", "criterion", "critic", "critical", "criticism", "criticize", "crook", "crop", "cross", "crow",
        "crown", "crucial", "crude", "cruel", "cruise", "cruiser", "crumb", "crumble", "crush", "crust",
        "crystal", "cube", "cubic", "cucumber", "cue", "cuff", "cuisine", "culminate", "cult", "cultivate",
        "cultivation", "culture", "cunning", "cupboard", "curb", "cure", "curiosity", "curious", "curl", "curry",
        "curse", "cursor", "curtain", "curve", "cushion", "custody", "custom", "customer", "customs", "cut",
        "cute", "cutter", "cycle", "cylinder", "cynical", "daily", "dairy", "dam", "damage", "damn",
        "damp", "dancer", "dare", "darken", "darling", "dart", "dash", "datum", "dazzle", "deadline",
        "deadly", "deaf", "dealer", "dean", "dearly", "death", "debate", "debit", "debt", "debut",
        "decay", "decease", "deceive", "decent", "decimal", "deck", "declaration", "declare", "decline", "decode",
        "decompose", "decorate", "decoration", "decorative", "decrease", "dedicate", "dedication", "deduce", "deduct", "deed",
        "deem", "deepen", "deer", "defeat", "defect", "defend", "defense", "deficiency", "deficit", "define",
        "definite", "definition", "deflect", "deform", "defrost", "defuse", "defy", "degrade", "degree", "delay",
        "delegate", "delegation", "delete", "deliberate", "delicate", "delicious", "delight", "deliver", "delivery", "delusion",
        "demand", "democracy", "democrat", "demographic", "demolish", "demon", "demonstrate", "demonstration", "denial", "denounce",
        "dense", "density", "dentist", "deny", "depart", "department", "departure", "depend", "dependence", "dependency",
        "depict", "deplete", "deploy", "deposit", "deposition", "depress", "depression", "deprive", "depth", "deputy",
        "derivation", "derive", "descend", "descent", "describe", "description", "desert", "deserve", "design", "designate",
        "designer", "desirable", "desire", "desolate", "despair", "desperate", "despite", "dessert", "destination", "destine",
        "destiny", "destroy", "destruction", "detach", "detail", "detain", "detect", "detection", "detective", "detector",
        "deter", "deteriorate", "determination", "determine", "detest", "detour", "detrimental", "develop", "development", "deviate",
        "device", "devise", "devoid", "devote", "devotion", "devour", "diabetes", "diagnose", "diagnosis", "diagram",
        "dial", "dialect", "diameter", "dictate", "dictation", "dictionary", "die", "differ", "differentiate", "difficult",
        "difficulty", "diffuse", "dig", "digest", "digit", "digital", "dignity", "dilemma", "diligent", "dimension",
        "diminish", "dine", "dinner", "dioxide", "diploma", "diplomat", "diplomatic", "direct", "direction", "directive",
        "directly", "director", "directory", "dirt", "disable", "disadvantage", "disagree", "disappear", "disappoint", "disapproval",
        "disapprove", "disarm", "disaster", "disastrous", "discard", "discern", "discharge", "discipline", "disclose", "disco",
        "discord", "discount", "discourage", "discourse", "discover", "discovery", "discredit", "disease", "disgrace", "disguise",
        "disgust", "dish", "dishonest", "disillusion", "disinfect", "dismal", "dismantle", "dismay", "dismiss", "disorder",
        "disperse", "displace", "display", "displease", "disposal", "dispose", "disposition", "dispute", "disrupt", "dissatisfaction",
        "dissatisfy", "dissect", "disseminate", "dissertation", "dissipate", "dissolve", "distance", "distant", "distil", "distinct",
        "distinction", "distinctive", "distinguish", "distort", "distract", "distress", "distribute", "distribution", "district", "distrust",
        "disturb", "disturbance", "ditch", "dive", "diverge", "diverse", "diversion", "divert", "divide", "dividend",
        "divine", "division", "divorce", "dizzy", "dock", "doctrine", "document", "documentary", "dodge", "doe",
        "dogma", "dole", "doll", "domain", "dome", "domestic", "dominant", "dominate", "dominion", "donate",
        "donation", "donor", "doom", "doorway", "dormitory", "dose", "dot", "double", "doubt", "dough",
        "dove", "down", "downfall", "downstairs", "downtown", "downward", "doze", "dozen", "draft", "drag",
        "dragon", "drain", "drainage", "drama", "dramatic", "drastic", "draw", "drawback", "drawer", "drawing",
        "dread", "dreadful", "dream", "dreary", "dress", "drift", "drill", "drink", "drip", "drive",
        "droit", "droll", "drone", "droop", "drop", "drought", "drown", "drowsy", "drudge", "drug",
        "drum", "drunk", "drunken", "dry", "dual", "dub", "dubious", "duchess", "duck", "duct",
        "dude", "due", "duke", "dull", "duly", "dumb", "dump", "dumpling", "dune", "dungeon",
        "duplicate", "durable", "duration", "during", "dusk", "dust", "duty", "dwarf", "dwell", "dwelling",
        "dwindle", "dye", "dynamic", "dynamics", "dynasty", "each", "eager", "eagle", "ear", "earl",
        "earlier", "earliest", "earring", "earth", "earthquake", "ease", "easily", "east", "Easter", "eastern",
        "eastward", "easy", "eat", "ebb", "eccentric", "echo", "eclipse", "ecology", "economic", "economics",
        "economist", "economy", "ecosystem", "edge", "edible", "edit", "edition", "editor", "editorial", "educate",
        "education", "educator", "effect", "effective", "efficiency", "efficient", "effort", "egg", "ego", "eight",
        "eighteen", "eighth", "eighty", "either", "eject", "elaborate", "elapse", "elastic", "elbow", "elder",
        "elderly", "elect", "election", "electric", "electrical", "electrician", "electricity", "electrify", "electron", "electronic",
        "electronics", "elegant", "element", "elementary", "elephant", "elevate", "elevator", "eleven", "eleventh", "elf",
        "elicit", "eligible", "eliminate", "elite", "else", "elsewhere", "elude", "elusive", "emancipate", "embark",
        "embarrass", "embassy", "embed", "embody", "embrace", "embroidery", "emerge", "emergency", "emigration", "eminent",
        "emit", "emotion", "emotional", "emperor", "emphasis", "emphasize", "empire", "empirical", "employ", "employee",
        "employer", "employment", "empower", "empress", "empty", "enable", "enact", "enamel", "encircle", "enclose",
        "enclosure", "encounter", "encourage", "encouragement", "encyclopedia", "end", "endanger", "endeavor", "endless", "endorse",
        "endow", "endurance", "endure", "enemy", "energetic", "energy", "enforce", "engage", "engagement", "engine",
        "engineer", "engineering", "English", "engrave", "enhance", "enjoy", "enjoyable", "enjoyment", "enlarge", "enlighten",
        "enormous", "enquire", "enquiry", "enrich", "enroll", "enrollment", "ensure", "entail", "enter", "enterprise",
        "entertain", "entertainment", "enthusiasm", "enthusiast", "enthusiastic", "entire", "entirely", "entity", "entitle", "entrance",
        "entrant", "entrepreneur", "entry", "envelope", "environment", "environmental", "envision", "envoy", "envy", "epidemic",
        "episode", "equal", "equality", "equation", "equator", "equip", "equipment", "equity", "equivalent", "era",
        "eradicate", "erase", "eraser", "erect", "erosion", "err", "errand", "erroneous", "error", "erupt",
        "eruption", "escalate", "escalator", "escape", "escort", "especially", "essay", "essence", "essential", "essentially",
        "establish", "establishment", "estate", "esteem", "esthetic", "estimate", "eternal", "ethics", "ethnic", "etiquette",
        "euphoria", "evacuate", "evaluate", "evaluation", "evaporate", "evasion", "eve", "even", "evening", "event",
        "eventual", "eventually", "ever", "everlasting", "every", "everybody", "everyday", "everyone", "everything", "everywhere",
        "evidence", "evident", "evil", "evoke", "evolution", "evolve", "exact", "exactly", "exaggerate", "examination",
        "examine", "example", "exceed", "excellence", "excellent", "except", "exception", "exceptional", "excess", "excessive",
        "exchange", "excite", "excitement", "exciting", "exclaim", "exclamation", "exclude", "exclusive", "exclusively", "excursion",
        "excuse", "execute", "execution", "executive", "exemplify", "exercise", "exert", "exhaust", "exhibit", "exhibition",
        "exile", "exist", "existence", "existent", "exit", "exodus", "exotic", "expand", "expansion", "expect",
        "expectation", "expedition", "expel", "expend", "expenditure", "expense", "expensive", "experience", "experiment", "experimental",
        "expert", "expertise", "expiration", "expire", "explain", "explanation", "explicit", "explode", "exploit", "exploration",
        "explore", "explorer", "explosion", "explosive", "export", "expose", "exposure", "express", "expression", "exquisite",
        "extend", "extension", "extensive", "extent", "exterior", "external", "extinct", "extinction", "extinguish", "extra",
        "extract", "extraordinary", "extravagant", "extreme", "extremely", "extrinsic", "eye", "eyebrow", "eyelash", "eyelid",
    ],
    3: [  # 中高难度词汇
        "aberration", "abhor", "abolition", "abreast", "abridge", "absolve", "abstain", "abundance", "accede", "accession",
        "acclaim", "accolade", "accomplished", "accord", "accost", "accrue", "accumulate", "accusation", "acerbic", "acknowledgment",
        "acquiesce", "acquit", "acrid", "acrimonious", "acumen", "adage", "adamant", "adaptation", "addiction", "additive",
        "adhesive", "adjourn", "adjudicate", "administer", "admonish", "admonition", "adorn", "adroit", "adulation", "adulterate",
        "adversary", "adversity", "advert", "advocacy", "aegis", "aesthetic", "affable", "affected", "affidavit", "affiliation",
        "affinity", "affirmation", "affliction", "affluent", "affordable", "affront", "agglomerate", "aggrandize", "aggregate", "aggrieve",
        "agile", "agitate", "agnostic", "agonize", "agrarian", "ailment", "airborne", "aisle", "alchemy", "alcove",
        "alias", "alibi", "alienate", "alimentary", "allay", "allegation", "allegiance", "allegory", "alleviate", "alliance",
        "alliteration", "allocate", "allot", "allotment", "allude", "allure", "allusion", "alms", "aloof", "alteration",
        "alternation", "altruism", "aluminium", "amalgamate", "amass", "ambidextrous", "ambience", "ambiguity", "ambivalent", "ambrosia",
        "ameliorate", "amenable", "amend", "amenity", "amiable", "amicable", "amity", "amnesty", "amoral", "amorous",
        "amorphous", "amphibian", "amplitude", "amulet", "anachronism", "analgesic", "analogous", "analogue", "analogy", "anarchy",
        "anathema", "anatomical", "ancestry", "ancillary", "andirons", "anecdote", "anemia", "anesthesia", "anguish", "animate",
        "animation", "animosity", "annals", "anneal", "annex", "annihilate", "annotate", "annuity", "anoint", "anomalous",
        "anomaly", "anonymity", "antagonism", "antagonist", "antecedent", "antediluvian", "antelope", "anterior", "anthology", "anthropology",
        "antibiotic", "antidote", "antipathy", "antiquated", "antique", "antiquity", "antiseptic", "antithesis", "anxiety", "apathy",
        "apex", "aphorism", "apiece", "aplomb", "apocalypse", "apocryphal", "apogee", "apologetic", "apostle", "apothecary",
        "apparition", "appease", "appellation", "append", "appertain", "applause", "applicable", "applicant", "appoint", "appointee",
        "appraisal", "appreciable", "apprehend", "apprehension", "apprentice", "apprise", "approbation", "appropriate", "appropriation", "approximation",
        "apron", "aptitude", "aquatic", "aqueous", "arable", "arbiter", "arbitrary", "arbitrate", "arboreal", "arcade",
        "archaeology", "archaic", "archbishop", "archetype", "archipelago", "architect", "archive", "ardent", "arduous", "aria",
        "arid", "aristocracy", "aristocrat", "armament", "armistice", "aroma", "aromatic", "arraign", "arrangement", "arrant",
        "arrear", "arrest", "arrogance", "arrogant", "arrogate", "arsenal", "arsenic", "artful", "artifice", "artisan",
        "artless", "ascertain", "ascetic", "ascribe", "aseptic", "ashamed", "asinine", "askance", "asparagus", "aspiration",
        "aspire", "assail", "assassin", "assault", "assay", "asseverate", "assiduous", "assignation", "assimilate", "assize",
        "assonance", "assort", "assuage", "assurance", "asteroid", "asthma", "astigmatism", "astound", "astringent", "astrology",
        "astronaut", "astronomer", "astronomy", "astute", "asunder", "atavism", "atheism", "atheist", "athletics", "atlas",
        "atonement", "atrocious", "atrocity", "atrophy", "attache", "attainment", "attestation", "attic", "attire", "attorney",
        "attribute", "attrition", "atypical", "auction", "audacious", "audacity", "audible", "audience", "audiophile", "augment",
        "augur", "august", "aura", "aural", "auricle", "auspices", "auspicious", "austere", "authentic", "authenticate",
        "authoritarian", "authoritative", "autocracy", "autocrat", "automaton", "autonomous", "autopsy", "autumnal", "auxiliary", "avarice",
        "avenge", "aver", "aversion", "avid", "avocation", "avow", "avowal", "await", "awaken", "award",
        "awe", "awesome", "awry", "axiom", "azure", "babble", "bacchanalian", "bachelor", "backbite", "backward",
        "badger", "badinage", "baffle", "bait", "bale", "baleful", "balk", "ballad", "ballast", "balmy",
        "balm", "banal", "bandanna", "bandy", "bane", "baneful", "bang", "banish", "banister", "banter",
        "barb", "barbarian", "barbarous", "bard", "barefaced", "barge", "bark", "baroque", "barrage", "barrister",
        "barter", "base", "bashful", "basic", "basil", "basin", "bask", "basso", "bastion", "bate",
        "baton", "batten", "bauble", "bawdy", "bayou", "bazaar", "beacon", "bead", "beagle", "beak",
        "beam", "bean", "bear", "bearable", "beard", "bearing", "beast", "beatitude", "beatify", "beatitude",
        "beau", "beautify", "beauty", "bebop", "becalm", "beckon", "become", "bedazzle", "bedeck", "bedlam",
        "bedridden", "bedrock", "beef", "beeline", "befall", "befit", "befriend", "befuddle", "beg", "beget",
        "beggar", "begin", "beginner", "beguile", "behalf", "behave", "behavior", "behead", "behold", "behemoth",
        "beholden", "behove", "belabor", "belated", "beleaguer", "belie", "belief", "belittle", "bellicose", "belligerent",
        "balm", "balsam", "balsamic", "bamboozle", "banality", "banal", "bangle", "banish", "banister", "bankrupt",
        "banner", "banns", "banquet", "banshee", "bantam", "banting", "banyan", "barb", "barbarian", "barbarism",
        "barbarity", "barbarous", "barbecue", "barbell", "barber", "bare", "barefoot", "bareheaded", "barely", "bargain",
        "barge", "baritone", "barium", "bark", "barley", "barmy", "barn", "barnacle", "barometer", "baron",
        "baroness", "baronet", "baronial", "barque", "barrack", "barrage", "barrel", "barren", "barricade", "barrier",
        "barrister", "barrow", "bartender", "barter", "basalt", "base", "baseball", "baseless", "bash", "bashful",
        "basic", "basically", "basics", "basil", "basin", "basis", "bask", "basket", "basketball", "bass",
        "basset", "bassoon", "bastard", "bastion", "bat", "batch", "bated", "bathe", "bathos", "bathroom",
        "baton", "batten", "batter", "battery", "battle", "battlefield", "bauble", "baulk", "bawdy", "bawl",
        "bay", "bayonet", "bazaar", "beach", "beacon", "bead", "beadle", "beagle", "beak", "beam",
        "bean", "bear", "beard", "beast", "beat", "beaten", "beater", "beatitude", "beatnik", "beau",
        "beautician", "beautiful", "beautify", "beauty", "beaver", "bebop", "because", "beck", "beckon", "become",
        "bed", "bedbug", "bedclothes", "bedding", "bedlam", "bedouin", "bedridden", "bedrock", "bedroom", "bedside",
        "bedtime", "bee", "beech", "beef", "beefsteak", "beehive", "beekeeper", "beeline", "beer", "beeswax",
        "beet", "beetle", "befall", "befit", "befitting", "beforehand", "befriend", "befuddled", "beg", "began",
        "beggar", "begin", "beginner", "beginning", "begot", "begotten", "begrudge", "beguile", "begun", "behalf",
        "behave", "behavior", "behead", "behind", "behold", "beholding", "behoove", "beige", "being", "belabor",
        "belated", "belay", "belch", "beleaguer", "belie", "belief", "believe", "belittle", "bellicose", "belligerent",
        "bellow", "bellows", "belly", "belong", "belongings", "beloved", "below", "belt", "belted", "bemoan",
        "bemused", "bencher", "bend", "beneath", "benediction", "benefactor", "benefice", "beneficial", "beneficiary", "benefit",
        "benevolence", "benevolent", "benign", "benignant", "bent", "benumb", "bequeath", "bequest", "berate", "bereave",
        "bereaved", "bereavement", "bereft", "beret", "berth", "beseech", "beseem", "beset", "besetting", "beside",
        "besides", "besiege", "besmear", "besmirch", "bespeak", "bespoken", "bestial", "bestir", "bestow", "bestrew",
        "bestride", "bet", "beta", "betake", "betel", "bethink", "betide", "betimes", "betoken", "betrayer",
        "betroth", "betrothal", "betrothed", "bets", "better", "betterment", "between", "betwixt", "bevel", "beverage",
        "bevy", "bewail", "beware", "bewilder", "bewitch", "beyond", "bias", "bib", "bible", "biblical",
        "bibliography", "bibliophile", "bibulous", "bicameral", "biceps", "bicker", "bicycle", "bid", "bide", "bidet",
        "biding", "biennial", "bier", "bifocals", "bifurcate", "bigamy", "bigot", "bigoted", "bigotry", "bijou",
        "bike", "bilateral", "bilge", "bilk", "bill", "billboard", "billet", "billfold", "billiards", "billion",
        "billow", "billows", "bin", "binary", "bind", "binder", "binding", "bindweed", "binge", "bingo",
        "binocular", "binoculars", "biography", "biological", "biology", "bionic", "bionics", "biopsy", "biorhythm", "biosphere",
        "biota", "biped", "bipartisan", "bipartite", "bipolar", "birch", "bird", "birdie", "birdlime", "birth",
        "birthplace", "birthright", "biscuit", "bisect", "bisexual", "bishop", "bishopric", "bismuth", "bison", "bistro",
        "bit", "biting", "bitter", "bitters", "bittern", "bittersweet", "bitty", "bitumen", "bituminous", "bivalve",
        "bivouac", "blab", "blabber", "blabbermouth", "black", "blackball", "blackberry", "blackboard", "blacken", "blackhead",
        "blackjack", "blacklist", "blackmail", "blackness", "blackout", "blacks", "blacksmith", "bladder", "blade", "blah",
        "blame", "blameworthy", "blanch", "bland", "blandishment", "blandness", "blank", "blanket", "blare", "blaspheme",
        "blasphemy", "blast", "blasted", "blatant", "blaze", "blazer", "blazon", "bleach", "bleak", "bleat",
        "bleed", "bleeder", "bleeding", "blemish", "blench", "blend", "bless", "blessed", "blessing", "blight",
        "blighted", "blind", "blinder", "blindfold", "blindness", "blink", "blinkered", "blip", "bliss", "blister",
        "blistering", "blithe", "blithely", "blitz", "blizzard", "bloated", "bloater", "blob", "block", "blockade",
        "blockage", "blockbuster", "blockhead", "blond", "blood", "bloodbath", "bloodhound", "bloodless", "bloodshed", "bloodshot",
        "bloodstain", "bloodstream", "bloodthirsty", "bloody", "bloom", "bloomer", "bloomers", "blooming", "blossom", "blot",
        "blotch", "blouse", "blow", "blower", "blowlamp", "blown", "blowout", "blowpipe", "blowsy", "blowzy",
        "blubber", "bludgeon", "blue", "bluebell", "blueberry", "bluebird", "bluebottle", "blueprint", "blues", "bluff",
        "blunder", "blunderbuss", "blunge", "blunt", "blurb", "blurt", "blush", "bluster", "boa", "boar",
        "board", "boarder", "boarding", "boardinghouse", "boardroom", "boards", "boardwalk", "boast", "boaster", "boat",
        "boater", "boatswain", "bob", "bobbin", "bobble", "bobby", "bobcat", "bode", "bodice", "bodily",
        "body", "bodyguard", "boer", "boffin", "bog", "bogey", "boggle", "boggy", "bogus", "bohemian",
        "boil", "boiler", "boisterous", "bold", "boldface", "bole", "bolster", "bolt", "bomb", "bombard",
        "bombardier", "bombardment", "bomber", "bombproof", "bombshell", "bombsight", "bonanza", "bond", "bondage", "bonded",
        "bondholder", "bonfire", "bonnet", "bonny", "bonanza", "bonsai", "bonus", "bony", "boo", "booby",
        "boodle", "book", "bookbindery", "bookbinder", "bookbinding", "bookcase", "bookend", "bookie", "booking", "bookish",
        "bookkeeper", "bookkeeping", "booklet", "bookmaker", "bookmark", "bookmobile", "bookplate", "bookseller", "bookshelf", "bookshop",
        "bookstall", "bookstore", "bookwork", "bookworm", "boom", "boomerang", "boon", "boondocks", "boor", "boost",
        "booster", "boot", "booted", "bootlace", "bootleg", "bootlicker", "boots", "booth", "booty", "booze",
        "boozer", "bopper", "borax", "bored", "boredom", "bore", "borer", "born", "borne", "boron",
        "borough", "borrow", "borrower", "borrowing", "borstal", "bort", "bosom", "bosomy", "boss", "bossy",
        "botanical", "botanist", "botany", "botch", "bote", "both", "bother", "botheration", "bothersome", "bottle",
        "bottlefeed", "bottleneck", "bottom", "bottomless", "botulism", "boudoir", "bouffant", "bough", "bought", "bouillabaisse",
        "bouillon", "boulder", "boulevard", "bounce", "bouncer", "bouncing", "bouncy", "bound", "boundary", "bounden",
        "boundless", "bounds", "bounteous", "bountiful", "bounty", "bouquet", "bourbon", "bourgeois", "bourgeoisie", "bourn",
        "bourse", "bout", "boutique", "bovine", "bovine", "bow", "bowdlerize", "bower", "bowing", "bowl",
        "bowler", "bowling", "bowman", "bowsprit", "bowyang", "box", "boxer", "boxing", "boxoffice", "boxwood",
        "boy", "boyar", "boycott", "boyfriend", "boyhood", "boyish", "bra", "brace", "bracelet", "bracelets",
        "brach", "bracken", "bracket", "brackish", "brag", "braggadocio", "braggart", "brahma", "brahman", "braid",
        "braille", "brain", "braincase", "brainchild", "brainpan", "brains", "brainstorm", "brainwash", "brainy", "braise",
        "brake", "bramble", "bran", "branch", "brand", "brandish", "brandy", "brash", "brass", "brassiere",
        "brassy", "brat", "bravado", "brave", "bravery", "bravo", "brawl", "brawn", "brawny", "bray",
        "brazen", "brazier", "breach", "bread", "breadbasket", "breadbox", "breadcrumb", "breaded", "breadfruit", "breadline",
        "breadth", "breadwinner", "break", "breakable", "breakage", "breakaway", "breakdown", "breaker", "breakfast", "breakneck",
        "breakout", "breakthrough", "breakup", "breakwater", "bream", "breast", "breastbone", "breastplate", "breaststroke", "breath",
        "breathalyse", "breathalyser", "breathe", "breather", "breathing", "breathless", "breathtaking", "bred", "breed", "breeder",
        "breeding", "breeze", "breezy", "brethren", "breve", "brevity", "brew", "brewer", "brewery", "brewis",
        "briar", "bribe", "bribery", "brick", "brickbat", "bricklayer", "brickwork", "bridal", "bride", "bridegroom",
        "bridesmaid", "bridge", "bridgework", "bridle", "brie", "brief", "briefing", "briefs", "brier", "brig",
        "brigade", "brigadier", "brigand", "bright", "brighten", "brilliance", "brilliant", "brim", "brimstone", "brindled",
        "brine", "bring", "brink", "brinkmanship", "briny", "brisk", "brisket", "bristle", "brit", "britches",
        "brittle", "broach", "broad", "broadcast", "broadcaster", "broadcasting", "broaden", "broadloom", "broadminded", "broadside",
        "broadsheet", "broadsword", "brocade", "brochure", "brogue", "broil", "broiler", "broke", "broken", "broker",
        "bromide", "bronchial", "bronchitis", "bronco", "brond", "bronze", "brooch", "brood", "broody", "brook",
        "broom", "broomstick", "broth", "brothel", "brother", "brotherhood", "brouhaha", "brow", "browbeat", "brown",
        "brownie", "brownish", "browse", "browser", "bruin", "bruise", "bruiser", "bruit", "brunch", "brunette",
        "brunt", "brush", "brushwood", "brushwork", "brusque", "brutal", "brutalize", "brutality", "brute", "bubble",
        "bubbly", "buccaneer", "buck", "buckaroo", "buckle", "buckram", "buckshot", "buckskin", "bucktooth", "buckwheat",
        "budge", "budget", "budgie", "budgerigar", "budge", "buff", "buffalo", "buffer", "buffet", "buffoon",
        "buffoonery", "bug", "bugbear", "bugger", "buggy", "buggy", "bughouse", "bugle", "bugr", "build",
        "builder", "building", "built", "bulb", "bulge", "bulk", "bulkhead", "bulky", "bull", "bulldog",
        "bulldoze", "bulldozer", "bullet", "bulletin", "bullets", "bullfight", "bullfighting", "bullfinch", "bullfrog", "bullhead",
        "bullhorn", "bullion", "bullish", "bullock", "bullshit", "bullseye", "bully", "bulwark", "bum", "bumble",
        "bumblebee", "bumboat", "bummer", "bump", "bumper", "bumpkin", "bumptious", "bumpy", "bun", "bunch",
        "buncombe", "bundle", "bungle", "bungling", "bunion", "bunk", "bunker", "bunkum", "bunny", "bunt",
        "buoy", "buoyancy", "bur", "burble", "burden", "burdensome", "burdock", "bureau", "bureaucracy", "bureaucrat",
        "burg", "burger", "burgher", "burglar", "burglary", "burgle", "burial", "burl", "burlesque", "burly",
        "burn", "burner", "burning", "burnish", "burnous", "burnt", "burp", "burro", "burrow", "burst",
        "burton", "bury", "bus", "busby", "bush", "bushel", "bushy", "business", "businesslike", "businessman",
        "busk", "busker", "busman", "bust", "bustard", "buster", "bustle", "busy", "busybody", "but",
        "butane", "butcher", "butchery", "butler", "butt", "butter", "buttercup", "butterfingers", "butterfly", "buttermilk",
        "butternut", "butterscotch", "buttery", "buttock", "buttocks", "button", "buttonhole", "buttress", "buxom", "buy",
        "buyer", "buzz", "buzzard", "buzzer", "bye", "byelaw", "bygone", "bygones", "bylaw", "bypass",
        "byplay", "byproduct", "bypath", "bypath", "bystander", "byway", "byways", "byword", "bye", "byzantine",
    ],
    4: [  # 高难度词汇
        "abecedarian", "aber", "aberdevine", "aberrant", "abhorrence", "abhorrent", "abidance", "abject", "abjure", "ablaze",
        "able", "ablution", "abnegation", "abnormal", "aboard", "abode", "abolitionist", "abominable", "abominate", "aboriginal",
        "aborigine", "abortifacient", "abortive", "abound", "abrasion", "abrasive", "abreast", "abridgment", "abrogate", "abscess",
        "abscissa", "abscond", "absentee", "absinthe", "absolute", "absolution", "absolutism", "absolve", "absorbent", "absorbing",
        "abstain", "abstention", "abstinence", "abstract", "abstruse", "absurd", "abundance", "abundant", "abuse", "abusive",
        "abut", "abysmal", "abyss", "acacia", "academe", "academician", "academy", "accede", "accelerando", "accelerator",
        "accent", "accentuate", "accept", "acceptance", "access", "accessary", "accessible", "accession", "accessory", "accidence",
        "accident", "accidental", "accipiter", "acclaim", "acclamation", "acclivity", "accolade", "accompanist", "accomplice", "accomplish",
        "accomplice", "accord", "accordance", "accordion", "accost", "account", "accountable", "accountancy", "accountant", "accounting",
        "accouter", "accoutrements", "accredit", "accretion", "accrue", "accumulate", "accumulation", "accumulative", "accumulator", "accuracy",
        "accurate", "accusation", "accusative", "accuse", "accustom", "acedia", "acephalous", "acerbic", "acerbity", "acetate",
        "acetic", "acetylene", "ache", "achene", "achieve", "achievement", "achromatism", "acid", "acidify", "acidity",
        "acidulous", "acknowledge", "aconite", "acorn", "acoustic", "acquaint", "acquaintance", "acquiesce", "acquiescence", "acquire",
        "acquisition", "acquisitive", "acquittal", "acquittance", "acre", "acreage", "acrid", "acrimonious", "acrimony", "acrobat",
        "acrobatic", "acrobatics", "acronym", "acrophobia", "acrostic", "act", "actinism", "actinium", "action", "activate",
        "activation", "activism", "activist", "activity", "actor", "actress", "acts", "actual", "actuality", "actuary",
        "actuation", "acuity", "acumen", "acupuncture", "acute", "adage", "adagio", "adamant", "adapt", "adaptation",
        "adapter", "adaption", "add", "addendum", "addict", "addiction", "addition", "additional", "additive", "address",
        "addressee", "adduce", "adept", "adequacy", "adequate", "adhere", "adherence", "adherent", "adhesion", "adhesive",
        "adieu", "adipose", "adj", "adjacent", "adjective", "adjoin", "adjourn", "adjournment", "adjudge", "adjudicate",
        "adjudication", "adjunct", "adjure", "adjust", "adjustable", "adjuster", "adjustment", "adjutant", "adman", "admin",
        "administer", "administration", "administrative", "administrator", "admirable", "admiral", "admiralty", "admiration", "admire", "admirer",
        "admissible", "admission", "admit", "admittance", "admix", "admonish", "admonition", "admonitory", "ado", "adobe",
        "adolescence", "adolescent", "adopt", "adoption", "adoptive", "adorable", "adoration", "adore", "adorn", "adornment",
        "adrenal", "adrenalin", "adrift", "adroitness", "adsorb", "adsorbent", "adsorption", "adulation", "adult", "adulterate",
        "adulteration", "adulterer", "adultery", "adumbrate", "advancement", "advantage", "advantageous", "advent", "adventist", "adventure",
        "adventurer", "adventurous", "adverb", "adverbial", "adversary", "adverse", "adversity", "advert", "advertise", "advertisement",
        "advertiser", "advertising", "advice", "advisable", "advise", "adviser", "advisor", "advisory", "advocate", "adz",
        "adze", "aegis", "aeolian", "aerate", "aeration", "aerial", "aerie", "aerobatics", "aerobatic", "aerobics",
        "aerodrome", "aerodynamics", "aeronaut", "aeronautics", "aeroplane", "aerosol", "aerospace", "aerostat", "aery", "aesthetic",
        "aesthetics", "aether", "afar", "affable", "affair", "affect", "affectation", "affected", "affection", "affectionate",
        "affidavit", "affiliate", "affiliation", "affinity", "affirm", "affirmation", "affirmative", "affix", "afflict", "affliction",
        "affluent", "afford", "affordable", "afforest", "affray", "affront", "aficionado", "afield", "afire", "aflame",
        "afloat", "afoot", "afraid", "afresh", "afrikaans", "afrikaner", "afro", "aft", "after", "afterbirth",
        "aftercare", "aftereffect", "afterglow", "afterlife", "aftermath", "afternoon", "afters", "aftershave", "aftertaste", "afterthought",
        "afterwards", "again", "against", "agape", "agate", "age", "ageing", "ageless", "agency", "agenda",
        "agent", "agglomeration", "agglutinate", "aggrandize", "aggravate", "aggregate", "aggregation", "aggression", "aggressive", "aggressor",
        "aggrieve", "aggrieved", "aghast", "agile", "agility", "agitate", "agitation", "agitator", "aglow", "agnail",
        "agnostic", "agnosticism", "ago", "agog", "agonise", "agonize", "agonized", "agonizing", "agony", "agoraphobia",
        "agoraphobic", "agrace", "agrarian", "agree", "agreeable", "agreement", "agricultural", "agriculturist", "agronomy", "aground",
        "ague", "ah", "aha", "ahem", "ahoy", "aid", "aide", "aids", "ailing", "ailment",
        "aim", "aimless", "ain't", "air", "airbase", "airbed", "airborne", "airbrake", "airbrush", "airbus",
        "aircraft", "aircrew", "airdrop", "airedale", "airfare", "airfield", "airflow", "airforce", "airgun", "airhostess",
        "airily", "airing", "airlane", "airless", "airline", "airliner", "airlock", "airmail", "airman", "airplane",
        "airport", "airproof", "airs", "airship", "airsick", "airsickness", "airspace", "airstrip", "airtight", "airway",
        "airwoman", "airy", "aisle", "ajar", "akimbo", "akin", "alabaster", "alack", "alacrity", "alameda",
        "alarm", "alarmist", "albatross", "albeit", "albino", "album", "albumen", "alchemist", "alchemy", "alcohol",
        "alcoholic", "alcoholism", "alcove", "alder", "alderman", "ale", "alehouse", "alert", "alfalfa", "alfresco",
        "algae", "algebra", "algorithm", "alias", "alibi", "alien", "alienate", "alienation", "alight", "align",
        "alignment", "alike", "aliment", "alimentary", "alimony", "aline", "alinement", "alive", "alkali", "alkaline",
        "all", "allah", "allay", "allegation", "allegiance", "allegory", "allegretto", "allegro", "alleluia", "allergy",
        "allergic", "alleviate", "alley", "alleyway", "alliance", "allied", "alligator", "alliteration", "alliterative", "allocate",
        "allocation", "allot", "allotment", "allow", "allowable", "allowance", "alloy", "allude", "allure", "allurement",
        "allusion", "allusive", "alluvial", "alluvium", "ally", "almanac", "almighty", "almoner", "alms", "aloe",
        "aloft", "aloin", "alone", "along", "alongside", "aloof", "aloud", "alp", "alpha", "alphabet",
        "alphabetic", "alphabetical", "alphabetically", "alpine", "already", "alright", "alsatian", "also", "altar", "altarpiece",
        "alter", "alteration", "altercation", "alternate", "alternative", "although", "altimeter", "altitude", "alto", "altogether",
        "altruism", "altruist", "alum", "aluminium", "aluminum", "alumnus", "alundum", "alveolar", "always", "amalgam",
        "amalgamate", "amandla", "amass", "amazon", "ambassador", "amber", "ambergris", "ambidextrous", "ambience", "ambient",
        "ambiguity", "ambiguous", "ambit", "ambition", "ambitious", "ambivalent", "amble", "ambrosia", "ambulance", "ambush",
        "ameba", "ameer", "ameliorate", "amenable", "amend", "amendment", "amends", "amenity", "ament", "american",
        "americanism", "amerindian", "amethyst", "amiable", "amicable", "amid", "amidships", "amigo", "amine", "amino",
        "amir", "amiss", "amity", "ammo", "ammonia", "ammonite", "amnesia", "amnesty", "amoeba", "amoebic",
        "amok", "among", "amongst", "amoral", "amorous", "amorphous", "amortise", "amortize", "amount", "amour",
        "amp", "ampere", "amphetamine", "amphibian", "amphibious", "amphitheater", "amphora", "ample", "amplifier", "amplify",
        "amplitude", "ampoule", "amputate", "amputee", "amulet", "amuse", "amusement", "amusing", "an", "anaconda",
        "anaemia", "anaemic", "anaesthesia", "anaesthetic", "anaesthetist", "anagram", "anal", "analgesia", "analgesic", "analog",
        "analogous", "analogue", "analogy", "analyse", "analysis", "analyst", "analytic", "analytical", "anarchic", "anarchism",
        "anarchist", "anarchy", "anathema", "anatomy", "ancestor", "ancestral", "ancestry", "anchor", "anchorage", "anchorman",
        "anchorwoman", "anchovy", "ancient", "ancillary", "and", "andante", "andirons", "androgynous", "anecdotal", "anecdote",
        "anemia", "anemone", "anew", "angel", "angelica", "angelus", "anger", "angle", "angler", "angles",
        "anglice", "anglican", "anglicism", "anglicize", "angling", "anglo", "anglophile", "anglophobe", "angry", "angstrom",
        "anguish", "angular", "animal", "animalcule", "animate", "animation", "animism", "animus", "ankle", "anklet",
        "ankush", "annals", "anneal", "annex", "annexation", "annexe", "annihilate", "anniversary", "anno", "annotate",
        "annotation", "announce", "announcement", "announcer", "annoy", "annoyance", "annual", "annuity", "annul", "annular",
        "annunciation", "anode", "anoint", "anomalous", "anomaly", "anon", "anonymity", "anonymous", "anopheles", "anorak",
        "anorexia", "another", "answer", "answerable", "ant", "antacid", "antagonism", "antagonist", "antagonize", "antarctic",
        "ante", "antecedent", "antecedents", "antediluvian", "antelope", "antenatal", "anteroom", "anthem", "anther", "anthill",
        "anthology", "anthrax", "anthropocentric", "anthropoid", "anthropologist", "anthropology", "anthropomorphic", "anthropomorphism", "anthropomorphize", "anti",
        "antiaircraft", "antibiotic", "antibody", "antic", "anticipate", "anticipation", "anticipatory", "anticlerical", "anticlockwise", "antics",
        "anticyclone", "antidote", "antihero", "antiknock", "antilogarithm", "antimacassar", "antimatter", "antimonial", "antimony", "antipathetic",
        "antipathy", "antipodean", "antipodes", "antiquarian", "antiquary", "antique", "antiquity", "antirrhinum", "antiseptic", "antisocial",
        "antithesis", "antitoxin", "antitrust", "antler", "antony", "antrum", "ants", "antique", "antiquated", "antique",
        "antiquary", "antiquarian", "antiquate", "antique", "antiquity", "antique", "antiquated", "antique", "antiquated", "antique",
    ],
    5: [  # 最高难度词汇（GRE级别）
        "abecedarian", "abhorrent", "abjure", "ablution", "abnegation", "abrogate", "abscond", "absinthe", "abstruse", "accede",
        "acclamation", "acclivity", "accoutre", "acerbic", "acquiesce", "acrid", "acrimonious", "acumen", "adage", "adamantine",
        "adduce", "adipose", "admonition", "adroit", "adulation", "adumbrate", "adventitious", "adversary", "aegis", "aeonian",
        "affable", "affinity", "afflatus", "affray", "agape", "aggrandize", "aggrieve", "agile", "agrestic", "akimbo",
        "alacrity", "aliment", "allay", "allegory", "alliteration", "alluvial", "aloof", "altercation", "amalgamate", "amaranth",
        "ambit", "ambrosial", "ameliorate", "amenable", "amorphous", "amortize", "amphibious", "amplitude", "amulet", "anachronism",
        "analgesic", "analogous", "anarchy", "anathema", "ancillary", "andirons", "animadversion", "animus", "annals", "anneal",
        "annihilate", "annuity", "anoint", "anomalous", "anomaly", "anonymity", "antagonism", "antecedent", "antediluvian", "anthology",
        "anthropomorphic", "antipathy", "antipodes", "antithesis", "apathetic", "aperture", "apex", "aphorism", "apiece", "aplomb",
        "apocalypse", "apocryphal", "apogee", "apolaustic", "apostasy", "apostate", "apothegm", "apotheosis", "appall", "appanage",
        "apparatchik", "apparition", "appease", "appellation", "append", "appertain", "applause", "apposite", "apprentice", "apprise",
        "approbation", "appurtenance", "apricot", "aprist", "apriority", "apron", "apse", "apterous", "aquatic", "aqueduct",
        "aqueous", "arabesque", "arable", "arbiter", "arbitrary", "arboreal", "arboretum", "arcane", "archaic", "archetype",
        "archipelago", "archive", "arcadian", "ardor", "arduous", "argot", "aria", "arid", "armament", "armistice",
        "aromatic", "arraign", "arrant", "arrear", "arrogate", "arsenal", "artesian", "artifice", "artisan", "artless",
        "ascendant", "ascetic", "aseptic", "asinine", "askance", "asperity", "aspersion", "aspiration", "assail", "assay",
        "asseverate", "assiduity", "assimilate", "assonance", "assuage", "asteroid", "astigmatism", "astral", "astringent", "astute",
        "asunder", "atavism", "atheism", "atoll", "atonement", "atrophic", "attache", "attainment", "attestation", "attire",
        "attribute", "attrition", "atypical", "au courant", "audacious", "audacity", "augment", "augur", "august", "aura",
        "aural", "auspices", "austere", "autocrat", "automaton", "autonomous", "autopsy", "auxiliary", "avarice", "aver",
        "averse", "aversion", "avid", "avocation", "avow", "avuncular", "awry", "axiom", "azure", "bacchanal",
        "badinage", "baffle", "bagatelle", "bailiwick", "bait", "baksheesh", "balderdash", "baleful", "balk", "ballast",
        "balm", "balmy", "banal", "bandy", "bane", "baneful", "banality", "banister", "bankrupt", "banner",
        "banns", "banter", "barb", "barbaric", "barbarous", "bard", "baroque", "barrage", "barrister", "barter",
        "bashful", "basilica", "bask", "bastion", "bate", "baton", "bauble", "bawdy", "bayou", "beacon",
        "beatific", "beatitude", "bedaub", "bedizen", "bedlam", "bedouin", "beef", "befuddle", "begrudge", "beguile",
        "behemoth", "beholden", "belabor", "belated", "beleaguer", "belie", "belittle", "bellicose", "belligerent", "balm",
        "bemoan", "bemused", "benign", "benison", "bequeath", "berate", "bereave", "bereft", "beret", "berserk",
        "beseech", "beset", "besmirch", "bestial", "bestow", "bete noire", "betroth", "betrothal", "betrothed", "bevy",
        "bewail", "bewitch", "bicameral", "bicker", "biennial", "bifurcate", "bigamy", "bigot", "bigotry", "bilge",
        "bilk", "billet", "billingsgate", "bilious", "bivouac", "blanch", "bland", "blandishment", "blare", "blasphemy",
        "blatant", "blazon", "bleak", "blighted", "blithe", "blithesome", "bloated", "bludgeon", "blueprint", "blunder",
        "blurt", "bluster", "bode", "bodkin", "bohemian", "boisterous", "bolster", "bombastic", "bonhomie", "bonny",
        "bonsai", "boor", "bootless", "booth", "booty", "booze", "borax", "bordello", "bore", "borgia",
        "borne", "borstal", "bosom", "botanical", "botch", "boudoir", "bough", "boulder", "boulevard", "bounce",
        "bounteous", "bountiful", "bourgeois", "bourgeoisie", "bourse", "bout", "boutique", "bovine", "bowdlerize", "bower",
        "bowl", "bowsprit", "box", "boycott", "brace", "bracken", "brackish", "braggadocio", "braggart", "braid",
        "braggart", "brandish", "brassy", "brawl", "brawn", "brawny", "bray", "brazen", "brazier", "breach",
        "breadth", "break", "bream", "breast", "breath", "breathtaking", "bred", "brethren", "brevity", "brew",
        "briar", "bribe", "bric-a-brac", "brine", "brink", "brisk", "bristle", "brittle", "broach", "brocade",
        "brochure", "brogue", "broil", "brood", "brook", "broom", "broth", "brothel", "browbeat", "bruit",
        "brusque", "brutal", "brute", "buccaneer", "bucolic", "buff", "buffalo", "buffoon", "bugaboo", "bugbear",
        "buggy", "bugle", "bulb", "bulge", "bulimia", "bulk", "bulldog", "bulldoze", "bulletin", "bullion",
        "bullock", "bulrush", "bulwark", "bumptious", "bun", "bungalow", "bungle", "bunion", "bunk", "bunker",
        "bunkum", "buncombe", "bunting", "buoy", "buoyant", "burden", "burdensome", "bureau", "bureaucracy", "burg",
        "burgeon", "burgess", "burgher", "burglar", "burlesque", "burly", "burnish", "burnous", "burro", "burrow",
        "bursar", "burst", "busby", "bushel", "business", "bust", "bustard", "bustle", "busybody", "butane",
        "butcher", "butler", "butt", "buttery", "buttock", "buttress", "buxom", "buy", "buzzard", "byelaw",
        "bygone", "byline", "bypass", "byproduct", "bypath", "bystander", "byway", "byword", "byzantine",
    ],
}

def generate_word_bank_data(bank_name: str, target_count: int, difficulty_range: tuple) -> list[dict]:
    """
    生成词库数据

    Args:
        bank_name: 词库名称
        target_count: 目标词汇数量
        difficulty_range: 难度范围 (min, max)

    Returns:
        词汇数据列表
    """
    words = []
    min_diff, max_diff = difficulty_range

    # 根据难度范围收集词汇
    available_words = []
    for diff in range(min_diff, max_diff + 1):
        if diff in VOCABULARY_BY_DIFFICULTY:
            available_words.extend([(w, diff) for w in VOCABULARY_BY_DIFFICULTY[diff]])

    # 如果可用词汇不够，重复使用
    while len(words) < target_count:
        for word, diff in available_words:
            if len(words) >= target_count:
                break

            # 生成词汇数据
            word_data = {
                "spelling": word,
                "phonetic": f"/{word[:3]}ˈ{word[3:] if len(word) > 3 else ''}/",  # 简化的音标生成
                "meaning": f"{'n.' if word[0].islower() else 'n.'} {word}",  # 简化的释义
                "example_sentence": f"This is an example for the word {word}.",
                "difficulty_level": diff,
                "order_index": len(words) + 1
            }
            words.append(word_data)

    return words[:target_count]


def generate_all_word_banks():
    """生成所有词库的数据文件"""
    data_dir = Path(__file__).parent.parent / "data"
    data_dir.mkdir(exist_ok=True)

    for bank_name, config in WORD_BANKS_CONFIG.items():
        print(f"Generating {bank_name}...")
        words = generate_word_bank_data(
            bank_name,
            config["target"],
            config["difficulty_range"]
        )

        # 保存为JSON文件
        output_file = data_dir / f"{bank_name}.json"
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump({"words": words}, f, ensure_ascii=False, indent=2)

        print(f"  Generated {len(words)} words for {bank_name}")

    print("\n✅ All word banks generated successfully!")
    print(f"📁 Data files saved to: {data_dir}")


if __name__ == "__main__":
    generate_all_word_banks()
