"""Word-bank seeding from the committed ECDICT-derived data files.

Seed data lives in ``backend/data/wordbanks/`` and is generated by
``scripts/build_wordbanks.py`` from the ECDICT dictionary (MIT licensed).
Keeping the data in version control means database initialization is
reproducible and works offline / in CI without any network access.

Seeding **reconciles by content**, not merely by existence. On a brownfield
database that already holds stale/placeholder banks (e.g. a legacy "生活英语"
bank with a handful of words), a naive "skip if any bank exists" guard would
leave that stale data in place forever — every deploy re-runs ``init_db`` but
the real ECDICT words would never land. Instead we:

  1. Drop banks that are no longer part of the expected set.
  2. Create expected banks that are missing.
  3. Rebuild an existing bank's word list when it differs from the data file,
     remapping any existing learning progress onto the new rows by spelling so
     a user's mastered words survive the reconcile.

This keeps ``init_db`` safe to run on every container start and self-heals a
production database that predates the full-library import (SOU-39 regression).
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Optional

from sqlalchemy.orm import Session

from app.models.progress import LearningProgress
from app.models.word import WordBank, Word

logger = logging.getLogger(__name__)

# backend/app/seed.py -> backend/data/wordbanks
DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "wordbanks"


def load_wordbank_files(data_dir: Optional[Path] = None) -> list[dict]:
    """Load bank definitions from ``index.json`` and their word files.

    Returns a list of dicts: ``{name, description, words: [...]}`` in the
    display order defined by ``index.json``.
    """
    data_dir = Path(data_dir) if data_dir else DATA_DIR
    index_path = data_dir / "index.json"
    if not index_path.exists():
        raise FileNotFoundError(
            f"Word-bank index not found: {index_path}. "
            f"Run scripts/build_wordbanks.py to generate seed data."
        )

    index = json.loads(index_path.read_text(encoding="utf-8"))
    banks: list[dict] = []
    for entry in index.get("banks", []):
        slug = entry["slug"]
        bank_path = data_dir / f"{slug}.json"
        bank = json.loads(bank_path.read_text(encoding="utf-8"))
        banks.append(bank)
    return banks


def _make_word(word_bank_id: int, index: int, w: dict) -> Word:
    return Word(
        word_bank_id=word_bank_id,
        spelling=w["spelling"],
        phonetic=w.get("phonetic") or None,
        meaning=w["meaning"],
        example_sentence=w.get("example_sentence") or None,
        order_index=w.get("order_index", index + 1),
    )


def _delete_bank_words(db: Session, bank_id: int) -> None:
    """Delete a bank's words and the learning progress that references them.

    Progress rows carry a NOT NULL FK to ``words.id``; they must be removed
    before (or together with) the words to satisfy the constraint.
    """
    word_ids = [wid for (wid,) in db.query(Word.id).filter(Word.word_bank_id == bank_id).all()]
    if word_ids:
        db.query(LearningProgress).filter(
            LearningProgress.word_id.in_(word_ids)
        ).delete(synchronize_session="fetch")
    db.query(Word).filter(Word.word_bank_id == bank_id).delete(synchronize_session="fetch")


def _rebuild_bank_words(db: Session, wb: WordBank, words: list[dict]) -> None:
    """Replace a bank's word rows with ``words``, preserving mastery by spelling.

    A user's ``LearningProgress`` references a specific ``word_id``. Rebuilding
    the word rows would orphan that progress, so we capture per-user mastery
    keyed by the (old) word's spelling, rebuild the rows, then re-create the
    progress against the new rows whose spelling matches. Progress for a
    spelling that no longer exists in the bank is dropped intentionally.

    The snapshots below query bare columns (tuples), not ORM instances, so the
    deleted rows never enter the session identity map — otherwise the freshly
    inserted rows (SQLite reuses vacated rowids) would collide with stale
    identities in the map.
    """
    old_id_to_spelling = dict(
        db.query(Word.id, Word.spelling).filter(Word.word_bank_id == wb.id).all()
    )

    # Snapshot progress rows for this bank's words as (user_id, spelling, ...).
    preserved: list[dict] = []
    if old_id_to_spelling:
        rows = (
            db.query(
                LearningProgress.word_id,
                LearningProgress.user_id,
                LearningProgress.is_mastered,
                LearningProgress.mastered_at,
            )
            .filter(LearningProgress.word_id.in_(list(old_id_to_spelling.keys())))
            .all()
        )
        for word_id, user_id, is_mastered, mastered_at in rows:
            preserved.append({
                "user_id": user_id,
                "spelling": old_id_to_spelling[word_id],
                "is_mastered": is_mastered,
                "mastered_at": mastered_at,
            })

    # Clear old words + their progress, then insert the fresh word list.
    _delete_bank_words(db, wb.id)
    db.flush()

    new_words = [_make_word(wb.id, i, w) for i, w in enumerate(words)]
    db.add_all(new_words)
    db.flush()  # assign ids so progress can be remapped

    if preserved:
        spelling_to_new_id = {w.spelling: w.id for w in new_words}
        for p in preserved:
            new_id = spelling_to_new_id.get(p["spelling"])
            if new_id is None:
                continue  # spelling gone from the new list; drop stale progress
            db.add(LearningProgress(
                user_id=p["user_id"],
                word_id=new_id,
                is_mastered=p["is_mastered"],
                mastered_at=p["mastered_at"],
            ))


def seed_wordbanks(db: Session, data_dir: Optional[Path] = None) -> int:
    """Reconcile word banks/words to the committed data files (idempotent).

    Returns the number of banks *created* this run (0 when everything already
    matches, so a repeat call is a no-op). Existing banks are reconciled in
    place and stale banks are removed.
    """
    banks = load_wordbank_files(data_dir)
    expected_names = {bank["name"] for bank in banks}

    # 1. Remove stale banks that are no longer part of the expected set.
    stale_banks = db.query(WordBank).filter(~WordBank.name.in_(expected_names)).all()
    for wb in stale_banks:
        logger.info("Removing stale word bank '%s'", wb.name)
        _delete_bank_words(db, wb.id)
        db.delete(wb)
    if stale_banks:
        db.flush()

    created = 0
    for bank in banks:
        words = bank.get("words", [])
        wb = db.query(WordBank).filter(WordBank.name == bank["name"]).first()

        if wb is None:
            # 2. Missing bank -> create it with its full word list.
            wb = WordBank(
                name=bank["name"],
                description=bank.get("description", ""),
                total_words=len(words),
            )
            db.add(wb)
            db.flush()
            db.add_all([_make_word(wb.id, i, w) for i, w in enumerate(words)])
            created += 1
            logger.info("Seeded word bank '%s' with %d words", wb.name, len(words))
            continue

        # 3. Existing bank -> reconcile only when the stored word set differs.
        existing_count = db.query(Word).filter(Word.word_bank_id == wb.id).count()
        if existing_count != len(words):
            logger.info(
                "Reconciling word bank '%s': %d -> %d words",
                wb.name, existing_count, len(words),
            )
            _rebuild_bank_words(db, wb, words)
        wb.description = bank.get("description", wb.description)
        wb.total_words = len(words)

    db.commit()
    return created
