"""Word-bank seeding from the committed ECDICT-derived data files.

Seed data lives in ``backend/data/wordbanks/`` and is generated by
``scripts/build_wordbanks.py`` from the ECDICT dictionary (MIT licensed).
Keeping the data in version control means database initialization is
reproducible and works offline / in CI without any network access.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Optional

from sqlalchemy.orm import Session

from app.models.word import WordBank, Word

logger = logging.getLogger(__name__)

# backend/app/seed.py -> backend/data/wordbanks
DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "wordbanks"


def load_wordbank_files(data_dir: Optional[Path] = None) -> list[dict]:
    """Load bank definitions from ``index.json`` and their word files.

    Returns a list of dicts: ``{name, description, words: [...]}`` in the
    display order defined by ``index.json``.
    """
    data_dir = Path(data_dir) if data_dir else DATA_DIR
    index_path = data_dir / "index.json"
    if not index_path.exists():
        raise FileNotFoundError(
            f"Word-bank index not found: {index_path}. "
            f"Run scripts/build_wordbanks.py to generate seed data."
        )

    index = json.loads(index_path.read_text(encoding="utf-8"))
    banks: list[dict] = []
    for entry in index.get("banks", []):
        slug = entry["slug"]
        bank_path = data_dir / f"{slug}.json"
        bank = json.loads(bank_path.read_text(encoding="utf-8"))
        banks.append(bank)
    return banks


def seed_wordbanks(db: Session, data_dir: Optional[Path] = None) -> int:
    """Idempotently seed word banks and words. Returns number of banks created.

    If any word bank already exists, seeding is skipped so that re-running
    ``init_db`` never duplicates data.
    """
    if db.query(WordBank).first():
        logger.info("Word banks already present; skipping seed.")
        return 0

    banks = load_wordbank_files(data_dir)
    created = 0
    for bank in banks:
        words = bank.get("words", [])
        wb = WordBank(
            name=bank["name"],
            description=bank.get("description", ""),
            total_words=len(words),
        )
        db.add(wb)
        db.flush()  # assign wb.id without a full commit round-trip

        db.bulk_save_objects([
            Word(
                word_bank_id=wb.id,
                spelling=w["spelling"],
                phonetic=w.get("phonetic") or None,
                meaning=w["meaning"],
                example_sentence=w.get("example_sentence") or None,
                order_index=w.get("order_index", i + 1),
            )
            for i, w in enumerate(words)
        ])
        created += 1
        logger.info("Seeded word bank '%s' with %d words", wb.name, len(words))

    db.commit()
    return created
